import type { PointSettings } from "@/lib/types";

export const POINT_SETTING_GROUPS = [
  [
    "Partidos de grupos",
    [
      "match_sign_points",
      "match_goal_difference_points",
      "match_exact_score_points",
    ],
  ],
  [
    "Grupos",
    [
      "group_exact_position_points",
      "group_winner_bonus_points",
      "group_qualified_team_points",
      "best_third_team_points",
    ],
  ],
  [
    "Cuadro inicial",
    [
      "knockout_round_32_reached_points",
      "knockout_round_16_reached_points",
      "knockout_quarter_reached_points",
      "knockout_semi_reached_points",
      "knockout_final_reached_points",
      "knockout_champion_points",
      "knockout_runner_up_points",
      "knockout_third_place_points",
    ],
  ],
  [
    "Partidos de eliminatoria",
    [
      "live_round_32_sign_points",
      "live_round_32_winner_points",
      "live_round_32_goal_difference_points",
      "live_round_32_exact_score_bonus",
      "live_round_16_sign_points",
      "live_round_16_winner_points",
      "live_round_16_goal_difference_points",
      "live_round_16_exact_score_bonus",
      "live_quarter_sign_points",
      "live_quarter_winner_points",
      "live_quarter_goal_difference_points",
      "live_quarter_exact_score_bonus",
      "live_semi_sign_points",
      "live_semi_winner_points",
      "live_semi_goal_difference_points",
      "live_semi_exact_score_bonus",
      "live_third_place_sign_points",
      "live_third_place_winner_points",
      "live_third_place_goal_difference_points",
      "live_third_place_exact_score_bonus",
      "live_final_sign_points",
      "live_final_winner_points",
      "live_final_goal_difference_points",
      "live_final_exact_score_bonus",
    ],
  ],
  ["Goleadores", ["scorer_goal_points", "scorer_max_points"]],
  [
    "Premios",
    [
      "award_top_scorer_points",
      "award_best_player_points",
      "award_best_goalkeeper_points",
      "award_best_young_player_points",
    ],
  ],
] as const satisfies ReadonlyArray<
  readonly [string, readonly (keyof Omit<PointSettings, "id" | "league_id">)[]]
>;

export const POINT_SETTING_LABELS: Record<
  keyof Omit<PointSettings, "id" | "league_id">,
  string
> = {
  match_sign_points: "Signo 1/X/2",
  match_goal_difference_points: "Diferencia de goles",
  match_exact_score_points: "Resultado exacto",
  group_exact_position_points: "Posicion exacta",
  group_winner_bonus_points: "Ganador de grupo",
  group_qualified_team_points: "Clasificado directo",
  best_third_team_points: "Mejor tercero",
  knockout_round_32_reached_points: "Llega a dieciseisavos",
  knockout_round_16_reached_points: "Llega a octavos",
  knockout_quarter_reached_points: "Llega a cuartos",
  knockout_semi_reached_points: "Llega a semifinales",
  knockout_final_reached_points: "Llega a la final",
  knockout_champion_points: "Campeon del torneo",
  knockout_runner_up_points: "Subcampeon",
  knockout_third_place_points: "Tercer puesto",
  live_round_32_sign_points: "Dieciseisavos 1/X/2",
  live_round_32_winner_points: "Dieciseisavos clasificado",
  live_round_32_goal_difference_points: "Dieciseisavos diferencia",
  live_round_32_exact_score_bonus: "Dieciseisavos exacto",
  live_round_16_sign_points: "Octavos 1/X/2",
  live_round_16_winner_points: "Octavos clasificado",
  live_round_16_goal_difference_points: "Octavos diferencia",
  live_round_16_exact_score_bonus: "Octavos exacto",
  live_quarter_sign_points: "Cuartos 1/X/2",
  live_quarter_winner_points: "Cuartos clasificado",
  live_quarter_goal_difference_points: "Cuartos diferencia",
  live_quarter_exact_score_bonus: "Cuartos exacto",
  live_semi_sign_points: "Semis 1/X/2",
  live_semi_winner_points: "Semis clasificado",
  live_semi_goal_difference_points: "Semis diferencia",
  live_semi_exact_score_bonus: "Semis exacto",
  live_third_place_sign_points: "Tercer puesto 1/X/2",
  live_third_place_winner_points: "Tercer puesto ganador",
  live_third_place_goal_difference_points: "Tercer puesto diferencia",
  live_third_place_exact_score_bonus: "Tercer puesto exacto",
  live_final_sign_points: "Final 1/X/2",
  live_final_winner_points: "Final clasificado",
  live_final_goal_difference_points: "Final diferencia",
  live_final_exact_score_bonus: "Final exacto",
  scorer_goal_points: "Gol",
  scorer_max_points: "Maximo goleadores",
  award_top_scorer_points: "Pichichi",
  award_best_player_points: "Mejor jugador",
  award_best_goalkeeper_points: "Mejor portero",
  award_best_young_player_points: "Mejor joven",
};
