alter table public.league_point_settings
  add column if not exists match_goal_difference_points int not null default 3,
  add column if not exists knockout_runner_up_points int not null default 35,
  add column if not exists knockout_third_place_points int not null default 20,
  add column if not exists live_round_32_sign_points int not null default 4,
  add column if not exists live_round_32_goal_difference_points int not null default 4,
  add column if not exists live_round_16_sign_points int not null default 4,
  add column if not exists live_round_16_goal_difference_points int not null default 4,
  add column if not exists live_quarter_sign_points int not null default 4,
  add column if not exists live_quarter_goal_difference_points int not null default 4,
  add column if not exists live_semi_sign_points int not null default 4,
  add column if not exists live_semi_goal_difference_points int not null default 4,
  add column if not exists live_third_place_sign_points int not null default 4,
  add column if not exists live_third_place_winner_points int not null default 0,
  add column if not exists live_third_place_goal_difference_points int not null default 4,
  add column if not exists live_third_place_exact_score_bonus int not null default 2,
  add column if not exists live_final_sign_points int not null default 6,
  add column if not exists live_final_goal_difference_points int not null default 6;

alter table public.league_point_settings
  alter column match_exact_score_points set default 3,
  alter column match_goal_difference_points set default 3,
  alter column match_sign_points set default 2,
  alter column group_exact_position_points set default 3,
  alter column group_winner_bonus_points set default 0,
  alter column group_qualified_team_points set default 5,
  alter column best_third_team_points set default 5,
  alter column knockout_round_32_reached_points set default 5,
  alter column knockout_round_16_reached_points set default 8,
  alter column knockout_quarter_reached_points set default 12,
  alter column knockout_semi_reached_points set default 18,
  alter column knockout_final_reached_points set default 25,
  alter column knockout_champion_points set default 60,
  alter column knockout_runner_up_points set default 35,
  alter column knockout_third_place_points set default 20,
  alter column live_round_32_sign_points set default 4,
  alter column live_round_32_winner_points set default 8,
  alter column live_round_32_goal_difference_points set default 4,
  alter column live_round_32_exact_score_bonus set default 2,
  alter column live_round_16_sign_points set default 4,
  alter column live_round_16_winner_points set default 12,
  alter column live_round_16_goal_difference_points set default 4,
  alter column live_round_16_exact_score_bonus set default 2,
  alter column live_quarter_sign_points set default 4,
  alter column live_quarter_winner_points set default 18,
  alter column live_quarter_goal_difference_points set default 4,
  alter column live_quarter_exact_score_bonus set default 2,
  alter column live_semi_sign_points set default 4,
  alter column live_semi_winner_points set default 25,
  alter column live_semi_goal_difference_points set default 4,
  alter column live_semi_exact_score_bonus set default 2,
  alter column live_third_place_sign_points set default 4,
  alter column live_third_place_winner_points set default 0,
  alter column live_third_place_goal_difference_points set default 4,
  alter column live_third_place_exact_score_bonus set default 2,
  alter column live_final_sign_points set default 6,
  alter column live_final_winner_points set default 0,
  alter column live_final_goal_difference_points set default 6,
  alter column live_final_exact_score_bonus set default 4,
  alter column award_top_scorer_points set default 25,
  alter column award_best_player_points set default 25,
  alter column award_best_goalkeeper_points set default 15,
  alter column award_best_young_player_points set default 15;

update public.league_point_settings
set
  match_exact_score_points = 3,
  match_goal_difference_points = 3,
  match_sign_points = 2,
  group_exact_position_points = 3,
  group_winner_bonus_points = 0,
  group_qualified_team_points = 5,
  best_third_team_points = 5,
  knockout_round_32_reached_points = 5,
  knockout_round_16_reached_points = 8,
  knockout_quarter_reached_points = 12,
  knockout_semi_reached_points = 18,
  knockout_final_reached_points = 25,
  knockout_champion_points = 60,
  knockout_runner_up_points = 35,
  knockout_third_place_points = 20,
  live_round_32_sign_points = 4,
  live_round_32_winner_points = 8,
  live_round_32_goal_difference_points = 4,
  live_round_32_exact_score_bonus = 2,
  live_round_16_sign_points = 4,
  live_round_16_winner_points = 12,
  live_round_16_goal_difference_points = 4,
  live_round_16_exact_score_bonus = 2,
  live_quarter_sign_points = 4,
  live_quarter_winner_points = 18,
  live_quarter_goal_difference_points = 4,
  live_quarter_exact_score_bonus = 2,
  live_semi_sign_points = 4,
  live_semi_winner_points = 25,
  live_semi_goal_difference_points = 4,
  live_semi_exact_score_bonus = 2,
  live_third_place_sign_points = 4,
  live_third_place_winner_points = 0,
  live_third_place_goal_difference_points = 4,
  live_third_place_exact_score_bonus = 2,
  live_final_sign_points = 6,
  live_final_winner_points = 0,
  live_final_goal_difference_points = 6,
  live_final_exact_score_bonus = 4,
  award_top_scorer_points = 25,
  award_best_player_points = 25,
  award_best_goalkeeper_points = 15,
  award_best_young_player_points = 15;
