-- Mundial 2026 actualizado a 2026-06-02.
-- Fuentes base:
-- - FIFA: grupos/equipos clasificados y calendario oficial de 104 partidos.
-- - PDF oficial FIFA v17 2026-04-10: emparejamientos y horas en ET.
-- - FIFA: fecha límite de listas definitivas (1 de junio) y confirmación oficial (2 de junio de 2026).
-- - Wikipedia 2026 FIFA World Cup squads: recopilación por selección cotejada con anuncios federativos.

insert into public.teams
  (name, short_name, flag_emoji, group_letter, fifa_ranking, manual_order)
values
  ('México', 'MEX', '🇲🇽', 'A', 16, 1),
  ('Sudáfrica', 'RSA', '🇿🇦', 'A', 60, 2),
  ('Corea del Sur', 'KOR', '🇰🇷', 'A', 22, 3),
  ('Chequia', 'CZE', '🇨🇿', 'A', 42, 4),
  ('Canadá', 'CAN', '🇨🇦', 'B', 29, 1),
  ('Suiza', 'SUI', '🇨🇭', 'B', 18, 2),
  ('Qatar', 'QAT', '🇶🇦', 'B', 51, 3),
  ('Bosnia y Herzegovina', 'BIH', '🇧🇦', 'B', 57, 4),
  ('Brasil', 'BRA', '🇧🇷', 'C', 5, 1),
  ('Marruecos', 'MAR', '🇲🇦', 'C', 8, 2),
  ('Haití', 'HAI', '🇭🇹', 'C', 84, 3),
  ('Escocia', 'SCO', '🏴', 'C', 36, 4),
  ('Estados Unidos', 'USA', '🇺🇸', 'D', 15, 1),
  ('Paraguay', 'PAR', '🇵🇾', 'D', 39, 2),
  ('Australia', 'AUS', '🇦🇺', 'D', 27, 3),
  ('Turquía', 'TUR', '🇹🇷', 'D', 34, 4),
  ('Alemania', 'GER', '🇩🇪', 'E', 10, 1),
  ('Curaçao', 'CUW', '🇨🇼', 'E', 82, 2),
  ('Costa de Marfil', 'CIV', '🇨🇮', 'E', 37, 3),
  ('Ecuador', 'ECU', '🇪🇨', 'E', 23, 4),
  ('Países Bajos', 'NED', '🇳🇱', 'F', 7, 1),
  ('Japón', 'JPN', '🇯🇵', 'F', 19, 2),
  ('Túnez', 'TUN', '🇹🇳', 'F', 47, 3),
  ('Suecia', 'SWE', '🇸🇪', 'F', 25, 4),
  ('Bélgica', 'BEL', '🇧🇪', 'G', 9, 1),
  ('Egipto', 'EGY', '🇪🇬', 'G', 31, 2),
  ('Irán', 'IRN', '🇮🇷', 'G', 20, 3),
  ('Nueva Zelanda', 'NZL', '🇳🇿', 'G', 86, 4),
  ('España', 'ESP', '🇪🇸', 'H', 2, 1),
  ('Cabo Verde', 'CPV', '🇨🇻', 'H', 68, 2),
  ('Arabia Saudí', 'KSA', '🇸🇦', 'H', 60, 3),
  ('Uruguay', 'URU', '🇺🇾', 'H', 17, 4),
  ('Francia', 'FRA', '🇫🇷', 'I', 1, 1),
  ('Senegal', 'SEN', '🇸🇳', 'I', 12, 2),
  ('Noruega', 'NOR', '🇳🇴', 'I', 32, 3),
  ('Irak', 'IRQ', '🇮🇶', 'I', 63, 4),
  ('Argentina', 'ARG', '🇦🇷', 'J', 3, 1),
  ('Argelia', 'ALG', '🇩🇿', 'J', 28, 2),
  ('Austria', 'AUT', '🇦🇹', 'J', 24, 3),
  ('Jordania', 'JOR', '🇯🇴', 'J', 64, 4),
  ('Portugal', 'POR', '🇵🇹', 'K', 5, 1),
  ('Uzbekistán', 'UZB', '🇺🇿', 'K', 52, 2),
  ('Colombia', 'COL', '🇨🇴', 'K', 14, 3),
  ('RD Congo', 'COD', '🇨🇩', 'K', 50, 4),
  ('Inglaterra', 'ENG', '🏴', 'L', 4, 1),
  ('Croacia', 'CRO', '🇭🇷', 'L', 11, 2),
  ('Ghana', 'GHA', '🇬🇭', 'L', 72, 3),
  ('Panamá', 'PAN', '🇵🇦', 'L', 33, 4)
on conflict (short_name) do update set
  name = excluded.name,
  flag_emoji = excluded.flag_emoji,
  group_letter = excluded.group_letter,
  fifa_ranking = excluded.fifa_ranking,
  manual_order = excluded.manual_order;

update public.teams
set flag_code = case short_name
  when 'MEX' then 'mx' when 'RSA' then 'za' when 'KOR' then 'kr' when 'CZE' then 'cz'
  when 'CAN' then 'ca' when 'SUI' then 'ch' when 'QAT' then 'qa' when 'BIH' then 'ba'
  when 'BRA' then 'br' when 'MAR' then 'ma' when 'HAI' then 'ht' when 'SCO' then 'gb-sct'
  when 'USA' then 'us' when 'PAR' then 'py' when 'AUS' then 'au' when 'TUR' then 'tr'
  when 'GER' then 'de' when 'CUW' then 'cw' when 'CIV' then 'ci' when 'ECU' then 'ec'
  when 'NED' then 'nl' when 'JPN' then 'jp' when 'TUN' then 'tn' when 'SWE' then 'se'
  when 'BEL' then 'be' when 'EGY' then 'eg' when 'IRN' then 'ir' when 'NZL' then 'nz'
  when 'ESP' then 'es' when 'CPV' then 'cv' when 'KSA' then 'sa' when 'URU' then 'uy'
  when 'FRA' then 'fr' when 'SEN' then 'sn' when 'NOR' then 'no' when 'IRQ' then 'iq'
  when 'ARG' then 'ar' when 'ALG' then 'dz' when 'AUT' then 'at' when 'JOR' then 'jo'
  when 'POR' then 'pt' when 'UZB' then 'uz' when 'COL' then 'co' when 'COD' then 'cd'
  when 'ENG' then 'gb-eng' when 'CRO' then 'hr' when 'GHA' then 'gh' when 'PAN' then 'pa'
  else flag_code
end;

update public.players
set is_active = false,
    is_star = false,
    scorer_rank = null;

with player_rows(name, short_name, position) as (
  values
    ('Matěj Kovář', 'CZE', 'GK'),
    ('David Zima', 'CZE', 'DF'),
    ('Tomáš Holeš', 'CZE', 'DF'),
    ('Robin Hranáč', 'CZE', 'DF'),
    ('Vladimír Coufal', 'CZE', 'DF'),
    ('Štěpán Chaloupek', 'CZE', 'DF'),
    ('Ladislav Krejčí', 'CZE', 'DF'),
    ('Vladimír Darida', 'CZE', 'MF'),
    ('Adam Hložek', 'CZE', 'FW'),
    ('Patrik Schick', 'CZE', 'FW'),
    ('Jan Kuchta', 'CZE', 'FW'),
    ('Lukáš Červ', 'CZE', 'MF'),
    ('Mojmír Chytil', 'CZE', 'FW'),
    ('David Jurásek', 'CZE', 'DF'),
    ('Pavel Šulc', 'CZE', 'FW'),
    ('Jindřich Staněk', 'CZE', 'GK'),
    ('Lukáš Provod', 'CZE', 'MF'),
    ('Michal Sadílek', 'CZE', 'MF'),
    ('Tomáš Chorý', 'CZE', 'FW'),
    ('Jaroslav Zelený', 'CZE', 'DF'),
    ('David Douděra', 'CZE', 'DF'),
    ('Tomáš Souček', 'CZE', 'MF'),
    ('Lukáš Horníček', 'CZE', 'GK'),
    ('Alexandr Sojka', 'CZE', 'MF'),
    ('Hugo Sochůrek', 'CZE', 'MF'),
    ('Denis Višinský', 'CZE', 'FW'),
    ('Raúl Rangel', 'MEX', 'GK'),
    ('Jorge Sánchez', 'MEX', 'DF'),
    ('César Montes', 'MEX', 'DF'),
    ('Edson Álvarez', 'MEX', 'DF'),
    ('Johan Vásquez', 'MEX', 'DF'),
    ('Érik Lira', 'MEX', 'MF'),
    ('Luis Romo', 'MEX', 'MF'),
    ('Álvaro Fidalgo', 'MEX', 'MF'),
    ('Raúl Jiménez', 'MEX', 'FW'),
    ('Alexis Vega', 'MEX', 'FW'),
    ('Santiago Giménez', 'MEX', 'FW'),
    ('Carlos Acevedo', 'MEX', 'GK'),
    ('Guillermo Ochoa', 'MEX', 'GK'),
    ('Armando González', 'MEX', 'FW'),
    ('Israel Reyes', 'MEX', 'DF'),
    ('Julián Quiñones', 'MEX', 'FW'),
    ('Orbelín Pineda', 'MEX', 'MF'),
    ('Obed Vargas', 'MEX', 'MF'),
    ('Gilberto Mora', 'MEX', 'MF'),
    ('Mateo Chávez', 'MEX', 'DF'),
    ('César Huerta', 'MEX', 'FW'),
    ('Guillermo Martínez', 'MEX', 'FW'),
    ('Jesús Gallardo', 'MEX', 'DF'),
    ('Luis Chávez', 'MEX', 'MF'),
    ('Roberto Alvarado', 'MEX', 'FW'),
    ('Brian Gutiérrez', 'MEX', 'MF'),
    ('Ronwen Williams', 'RSA', 'GK'),
    ('Thabang Matuludi', 'RSA', 'DF'),
    ('Khulumani Ndamane', 'RSA', 'DF'),
    ('Teboho Mokoena', 'RSA', 'MF'),
    ('Thalente Mbatha', 'RSA', 'MF'),
    ('Aubrey Modiba', 'RSA', 'DF'),
    ('Oswin Appollis', 'RSA', 'FW'),
    ('Tshepang Moremi', 'RSA', 'FW'),
    ('Lyle Foster', 'RSA', 'FW'),
    ('Relebohile Mofokeng', 'RSA', 'FW'),
    ('Themba Zwane', 'RSA', 'MF'),
    ('Thapelo Maseko', 'RSA', 'FW'),
    ('Sphephelo Sithole', 'RSA', 'MF'),
    ('Mbekezeli Mbokazi', 'RSA', 'DF'),
    ('Iqraam Rayners', 'RSA', 'FW'),
    ('Sipho Chaine', 'RSA', 'GK'),
    ('Evidence Makgopa', 'RSA', 'FW'),
    ('Samukele Kabini', 'RSA', 'DF'),
    ('Nkosinathi Sibisi', 'RSA', 'DF'),
    ('Khuliso Mudau', 'RSA', 'DF'),
    ('Ime Okon', 'RSA', 'DF'),
    ('Ricardo Goss', 'RSA', 'GK'),
    ('Jayden Adams', 'RSA', 'MF'),
    ('Olwethu Makhanya', 'RSA', 'DF'),
    ('Kamogelo Sebelebele', 'RSA', 'FW'),
    ('Bradley Cross', 'RSA', 'DF'),
    ('Kim Seung-gyu', 'KOR', 'GK'),
    ('Lee Han-beom', 'KOR', 'DF'),
    ('Lee Ki-hyuk', 'KOR', 'MF'),
    ('Kim Min-jae', 'KOR', 'DF'),
    ('Kim Tae-hyeon', 'KOR', 'DF'),
    ('Hwang In-beom', 'KOR', 'MF'),
    ('Son Heung-min', 'KOR', 'FW'),
    ('Paik Seung-ho', 'KOR', 'MF'),
    ('Cho Gue-sung', 'KOR', 'FW'),
    ('Lee Jae-sung', 'KOR', 'MF'),
    ('Hwang Hee-chan', 'KOR', 'MF'),
    ('Song Bum-keun', 'KOR', 'GK'),
    ('Lee Tae-seok', 'KOR', 'DF'),
    ('Cho Wi-je', 'KOR', 'DF'),
    ('Kim Moon-hwan', 'KOR', 'DF'),
    ('Park Jin-seob', 'KOR', 'DF'),
    ('Bae Jun-ho', 'KOR', 'MF'),
    ('Oh Hyeon-gyu', 'KOR', 'FW'),
    ('Lee Kang-in', 'KOR', 'MF'),
    ('Yang Hyun-jun', 'KOR', 'MF'),
    ('Jo Hyeon-woo', 'KOR', 'GK'),
    ('Seol Young-woo', 'KOR', 'DF'),
    ('Jens Castrop', 'KOR', 'DF'),
    ('Kim Jin-gyu', 'KOR', 'MF'),
    ('Eom Ji-sung', 'KOR', 'MF'),
    ('Lee Dong-gyeong', 'KOR', 'MF'),
    ('Nikola Vasilj', 'BIH', 'GK'),
    ('Nihad Mujakić', 'BIH', 'DF'),
    ('Dennis Hadžikadunić', 'BIH', 'DF'),
    ('Tarik Muharemović', 'BIH', 'DF'),
    ('Sead Kolašinac', 'BIH', 'DF'),
    ('Benjamin Tahirović', 'BIH', 'MF'),
    ('Amar Dedić', 'BIH', 'DF'),
    ('Armin Gigović', 'BIH', 'MF'),
    ('Samed Baždar', 'BIH', 'FW'),
    ('Ermedin Demirović', 'BIH', 'FW'),
    ('Edin Džeko', 'BIH', 'FW'),
    ('Mladen Jurkas', 'BIH', 'GK'),
    ('Ivan Bašić', 'BIH', 'MF'),
    ('Ivan Šunjić', 'BIH', 'MF'),
    ('Amar Memić', 'BIH', 'MF'),
    ('Amir Hadžiahmetović', 'BIH', 'MF'),
    ('Dženis Burnić', 'BIH', 'MF'),
    ('Nikola Katić', 'BIH', 'DF'),
    ('Kerim Alajbegović', 'BIH', 'FW'),
    ('Esmir Bajraktarević', 'BIH', 'FW'),
    ('Stjepan Radeljić', 'BIH', 'DF'),
    ('Martin Zlomislić', 'BIH', 'GK'),
    ('Haris Tabaković', 'BIH', 'FW'),
    ('Nidal Čelik', 'BIH', 'DF'),
    ('Jovo Lukić', 'BIH', 'FW'),
    ('Ermin Mahmić', 'BIH', 'MF'),
    ('Dayne St. Clair', 'CAN', 'GK'),
    ('Alistair Johnston', 'CAN', 'DF'),
    ('Alfie Jones', 'CAN', 'DF'),
    ('Luc de Fougerolles', 'CAN', 'DF'),
    ('Joel Waterman', 'CAN', 'DF'),
    ('Mathieu Choinière', 'CAN', 'MF'),
    ('Stephen Eustáquio', 'CAN', 'MF'),
    ('Ismaël Koné', 'CAN', 'MF'),
    ('Cyle Larin', 'CAN', 'FW'),
    ('Jonathan David', 'CAN', 'FW'),
    ('Liam Millar', 'CAN', 'MF'),
    ('Tani Oluwaseyi', 'CAN', 'FW'),
    ('Derek Cornelius', 'CAN', 'DF'),
    ('Jacob Shaffelburg', 'CAN', 'MF'),
    ('Moïse Bombito', 'CAN', 'DF'),
    ('Maxime Crépeau', 'CAN', 'GK'),
    ('Tajon Buchanan', 'CAN', 'FW'),
    ('Owen Goodman', 'CAN', 'GK'),
    ('Alphonso Davies', 'CAN', 'DF'),
    ('Ali Ahmed', 'CAN', 'FW'),
    ('Jonathan Osorio', 'CAN', 'MF'),
    ('Richie Laryea', 'CAN', 'DF'),
    ('Niko Sigur', 'CAN', 'DF'),
    ('Promise David', 'CAN', 'FW'),
    ('Nathan Saliba', 'CAN', 'MF'),
    ('Marcelo Flores', 'CAN', 'MF'),
    ('Mahmud Abunada', 'QAT', 'GK'),
    ('Pedro Miguel', 'QAT', 'DF'),
    ('Lucas Mendes', 'QAT', 'DF'),
    ('Issa Laye', 'QAT', 'DF'),
    ('Jassem Gaber', 'QAT', 'DF'),
    ('Abdulaziz Hatem', 'QAT', 'MF'),
    ('Ahmed Alaaeldin', 'QAT', 'FW'),
    ('Edmilson Junior', 'QAT', 'FW'),
    ('Mohammed Muntari', 'QAT', 'FW'),
    ('Hassan Al-Haydos', 'QAT', 'FW'),
    ('Akram Afif', 'QAT', 'FW'),
    ('Karim Boudiaf', 'QAT', 'MF'),
    ('Ayoub Al-Oui', 'QAT', 'DF'),
    ('Homam Ahmed', 'QAT', 'DF'),
    ('Yusuf Abdurisag', 'QAT', 'FW'),
    ('Boualem Khoukhi', 'QAT', 'DF'),
    ('Ahmed Al-Ganehi', 'QAT', 'MF'),
    ('Sultan Al-Brake', 'QAT', 'DF'),
    ('Almoez Ali', 'QAT', 'FW'),
    ('Ahmed Fathy', 'QAT', 'MF'),
    ('Salah Zakaria', 'QAT', 'GK'),
    ('Meshaal Barsham', 'QAT', 'GK'),
    ('Assim Madibo', 'QAT', 'MF'),
    ('Tahsin Jamshid', 'QAT', 'FW'),
    ('Al-Hashmi Al-Hussain', 'QAT', 'DF'),
    ('Mohamed Al-Mannai', 'QAT', 'FW'),
    ('Gregor Kobel', 'SUI', 'GK'),
    ('Miro Muheim', 'SUI', 'DF'),
    ('Silvan Widmer', 'SUI', 'DF'),
    ('Nico Elvedi', 'SUI', 'DF'),
    ('Manuel Akanji', 'SUI', 'DF'),
    ('Denis Zakaria', 'SUI', 'MF'),
    ('Breel Embolo', 'SUI', 'FW'),
    ('Remo Freuler', 'SUI', 'MF'),
    ('Johan Manzambi', 'SUI', 'MF'),
    ('Granit Xhaka', 'SUI', 'MF'),
    ('Dan Ndoye', 'SUI', 'FW'),
    ('Yvon Mvogo', 'SUI', 'GK'),
    ('Ricardo Rodriguez', 'SUI', 'DF'),
    ('Ardon Jashari', 'SUI', 'MF'),
    ('Djibril Sow', 'SUI', 'MF'),
    ('Christian Fassnacht', 'SUI', 'FW'),
    ('Rubén Vargas', 'SUI', 'FW'),
    ('Eray Cömert', 'SUI', 'DF'),
    ('Noah Okafor', 'SUI', 'FW'),
    ('Michel Aebischer', 'SUI', 'MF'),
    ('Marvin Keller', 'SUI', 'GK'),
    ('Fabian Rieder', 'SUI', 'MF'),
    ('Zeki Amdouni', 'SUI', 'FW'),
    ('Aurèle Amenda', 'SUI', 'DF'),
    ('Luca Jaquez', 'SUI', 'DF'),
    ('Cedric Itten', 'SUI', 'FW'),
    ('Alisson', 'BRA', 'GK'),
    ('Wesley', 'BRA', 'DF'),
    ('Gabriel Magalhães', 'BRA', 'DF'),
    ('Marquinhos', 'BRA', 'DF'),
    ('Casemiro', 'BRA', 'MF'),
    ('Alex Sandro', 'BRA', 'DF'),
    ('Vinícius Júnior', 'BRA', 'FW'),
    ('Bruno Guimarães', 'BRA', 'MF'),
    ('Matheus Cunha', 'BRA', 'FW'),
    ('Neymar', 'BRA', 'FW'),
    ('Raphinha', 'BRA', 'FW'),
    ('Weverton', 'BRA', 'GK'),
    ('Danilo Luiz', 'BRA', 'DF'),
    ('Bremer', 'BRA', 'DF'),
    ('Léo Pereira', 'BRA', 'DF'),
    ('Douglas Santos', 'BRA', 'DF'),
    ('Fabinho', 'BRA', 'MF'),
    ('Danilo Santos', 'BRA', 'MF'),
    ('Endrick', 'BRA', 'FW'),
    ('Lucas Paquetá', 'BRA', 'MF'),
    ('Luiz Henrique', 'BRA', 'FW'),
    ('Gabriel Martinelli', 'BRA', 'FW'),
    ('Ederson', 'BRA', 'GK'),
    ('Roger Ibañez', 'BRA', 'DF'),
    ('Igor Thiago', 'BRA', 'FW'),
    ('Rayan', 'BRA', 'FW'),
    ('Johny Placide', 'HAI', 'GK'),
    ('Carlens Arcus', 'HAI', 'DF'),
    ('Keeto Thermoncy', 'HAI', 'DF'),
    ('Ricardo Adé', 'HAI', 'DF'),
    ('Hannes Delcroix', 'HAI', 'DF'),
    ('Carl Sainté', 'HAI', 'MF'),
    ('Derrick Etienne Jr.', 'HAI', 'FW'),
    ('Martin Expérience', 'HAI', 'DF'),
    ('Duckens Nazon', 'HAI', 'FW'),
    ('Jean-Ricner Bellegarde', 'HAI', 'MF'),
    ('Louicius Deedson', 'HAI', 'FW'),
    ('Alexandre Pierre', 'HAI', 'GK'),
    ('Duke Lacroix', 'HAI', 'DF'),
    ('Leverton Pierre', 'HAI', 'MF'),
    ('Ruben Providence', 'HAI', 'FW'),
    ('Lenny Joseph', 'HAI', 'FW'),
    ('Danley Jean Jacques', 'HAI', 'MF'),
    ('Wilson Isidor', 'HAI', 'FW'),
    ('Yassin Fortuné', 'HAI', 'FW'),
    ('Frantzdy Pierrot', 'HAI', 'FW'),
    ('Josué Casimir', 'HAI', 'FW'),
    ('Jean-Kévin Duverne', 'HAI', 'DF'),
    ('Josué Duverger', 'HAI', 'GK'),
    ('Wilguens Paugain', 'HAI', 'DF'),
    ('Dominique Simon', 'HAI', 'MF'),
    ('Woodensky Pierre', 'HAI', 'MF'),
    ('Yassine Bounou', 'MAR', 'GK'),
    ('Achraf Hakimi', 'MAR', 'DF'),
    ('Noussair Mazraoui', 'MAR', 'DF'),
    ('Sofyan Amrabat', 'MAR', 'MF'),
    ('Nayef Aguerd', 'MAR', 'DF'),
    ('Ayyoub Bouaddi', 'MAR', 'MF'),
    ('Chemsdine Talbi', 'MAR', 'MF'),
    ('Azzedine Ounahi', 'MAR', 'MF'),
    ('Soufiane Rahimi', 'MAR', 'FW'),
    ('Brahim Díaz', 'MAR', 'FW'),
    ('Ismael Saibari', 'MAR', 'MF'),
    ('Munir Mohamedi', 'MAR', 'GK'),
    ('Zakaria El Ouahdi', 'MAR', 'DF'),
    ('Issa Diop', 'MAR', 'DF'),
    ('Samir El Mourabet', 'MAR', 'MF'),
    ('Gessime Yassine', 'MAR', 'MF'),
    ('Abde Ezzalzouli', 'MAR', 'FW'),
    ('Chadi Riad', 'MAR', 'DF'),
    ('Youssef Belammari', 'MAR', 'DF'),
    ('Ayoub El Kaabi', 'MAR', 'FW'),
    ('Ayoube Amaimouni', 'MAR', 'FW'),
    ('Ahmed Reda Tagnaouti', 'MAR', 'GK'),
    ('Bilal El Khannouss', 'MAR', 'MF'),
    ('Neil El Aynaoui', 'MAR', 'MF'),
    ('Redouane Halhal', 'MAR', 'DF'),
    ('Anass Salah-Eddine', 'MAR', 'DF'),
    ('Angus Gunn', 'SCO', 'GK'),
    ('Aaron Hickey', 'SCO', 'DF'),
    ('Andy Robertson', 'SCO', 'DF'),
    ('Scott McTominay', 'SCO', 'MF'),
    ('Grant Hanley', 'SCO', 'DF'),
    ('Kieran Tierney', 'SCO', 'DF'),
    ('John McGinn', 'SCO', 'MF'),
    ('Tyler Fletcher', 'SCO', 'MF'),
    ('Lyndon Dykes', 'SCO', 'FW'),
    ('Ché Adams', 'SCO', 'FW'),
    ('Ryan Christie', 'SCO', 'MF'),
    ('Liam Kelly', 'SCO', 'GK'),
    ('Jack Hendry', 'SCO', 'DF'),
    ('Ross Stewart', 'SCO', 'FW'),
    ('John Souttar', 'SCO', 'DF'),
    ('Dominic Hyam', 'SCO', 'DF'),
    ('Ben Gannon-Doak', 'SCO', 'FW'),
    ('George Hirst', 'SCO', 'FW'),
    ('Lewis Ferguson', 'SCO', 'MF'),
    ('Lawrence Shankland', 'SCO', 'FW'),
    ('Craig Gordon', 'SCO', 'GK'),
    ('Nathan Patterson', 'SCO', 'DF'),
    ('Kenny McLean', 'SCO', 'MF'),
    ('Anthony Ralston', 'SCO', 'DF'),
    ('Findlay Curtis', 'SCO', 'FW'),
    ('Scott McKenna', 'SCO', 'DF'),
    ('Mathew Ryan', 'AUS', 'GK'),
    ('Miloš Degenek', 'AUS', 'DF'),
    ('Alessandro Circati', 'AUS', 'DF'),
    ('Jacob Italiano', 'AUS', 'DF'),
    ('Jordan Bos', 'AUS', 'DF'),
    ('Jason Geria', 'AUS', 'DF'),
    ('Mathew Leckie', 'AUS', 'FW'),
    ('Connor Metcalfe', 'AUS', 'MF'),
    ('Mohamed Touré', 'AUS', 'FW'),
    ('Ajdin Hrustic', 'AUS', 'FW'),
    ('Awer Mabil', 'AUS', 'FW'),
    ('Paul Izzo', 'AUS', 'GK'),
    ('Aiden O''Neill', 'AUS', 'MF'),
    ('Cammy Devlin', 'AUS', 'MF'),
    ('Kai Trewin', 'AUS', 'DF'),
    ('Aziz Behich', 'AUS', 'DF'),
    ('Nestory Irankunda', 'AUS', 'FW'),
    ('Patrick Beach', 'AUS', 'GK'),
    ('Harry Souttar', 'AUS', 'DF'),
    ('Cristian Volpato', 'AUS', 'FW'),
    ('Cameron Burgess', 'AUS', 'DF'),
    ('Jackson Irvine', 'AUS', 'MF'),
    ('Nishan Velupillay', 'AUS', 'FW'),
    ('Paul Okon-Engstler', 'AUS', 'MF'),
    ('Lucas Herrington', 'AUS', 'DF'),
    ('Tete Yengi', 'AUS', 'FW'),
    ('Gatito Fernández', 'PAR', 'GK'),
    ('Gustavo Velázquez', 'PAR', 'DF'),
    ('Omar Alderete', 'PAR', 'DF'),
    ('Juan José Cáceres', 'PAR', 'DF'),
    ('Fabián Balbuena', 'PAR', 'DF'),
    ('Júnior Alonso', 'PAR', 'DF'),
    ('Ramón Sosa', 'PAR', 'MF'),
    ('Diego Gómez', 'PAR', 'MF'),
    ('Antonio Sanabria', 'PAR', 'FW'),
    ('Miguel Almirón', 'PAR', 'MF'),
    ('Maurício', 'PAR', 'MF'),
    ('Orlando Gill', 'PAR', 'GK'),
    ('José Canale', 'PAR', 'DF'),
    ('Andrés Cubas', 'PAR', 'MF'),
    ('Gustavo Gómez', 'PAR', 'DF'),
    ('Damián Bobadilla', 'PAR', 'MF'),
    ('Kaku', 'PAR', 'FW'),
    ('Álex Arce', 'PAR', 'FW'),
    ('Julio Enciso', 'PAR', 'FW'),
    ('Braian Ojeda', 'PAR', 'MF'),
    ('Gabriel Ávalos', 'PAR', 'FW'),
    ('Gastón Olveira', 'PAR', 'GK'),
    ('Matías Galarza', 'PAR', 'MF'),
    ('Gustavo Caballero', 'PAR', 'MF'),
    ('Isidro Pitta', 'PAR', 'FW'),
    ('Alexandro Maidana', 'PAR', 'DF'),
    ('Mert Günok', 'TUR', 'GK'),
    ('Zeki Çelik', 'TUR', 'DF'),
    ('Merih Demiral', 'TUR', 'DF'),
    ('Çağlar Söyüncü', 'TUR', 'DF'),
    ('Salih Özcan', 'TUR', 'MF'),
    ('Orkun Kökçü', 'TUR', 'MF'),
    ('Kerem Aktürkoğlu', 'TUR', 'FW'),
    ('Arda Güler', 'TUR', 'FW'),
    ('Deniz Gül', 'TUR', 'FW'),
    ('Hakan Çalhanoğlu', 'TUR', 'MF'),
    ('Kenan Yıldız', 'TUR', 'FW'),
    ('Altay Bayındır', 'TUR', 'GK'),
    ('Eren Elmalı', 'TUR', 'DF'),
    ('Abdülkerim Bardakcı', 'TUR', 'DF'),
    ('Ozan Kabak', 'TUR', 'DF'),
    ('İsmail Yüksek', 'TUR', 'MF'),
    ('İrfan Can Kahveci', 'TUR', 'FW'),
    ('Mert Müldür', 'TUR', 'DF'),
    ('Yunus Akgün', 'TUR', 'FW'),
    ('Ferdi Kadıoğlu', 'TUR', 'DF'),
    ('Barış Alper Yılmaz', 'TUR', 'FW'),
    ('Kaan Ayhan', 'TUR', 'MF'),
    ('Uğurcan Çakır', 'TUR', 'GK'),
    ('Oğuz Aydın', 'TUR', 'FW'),
    ('Samet Akaydin', 'TUR', 'DF'),
    ('Can Uzun', 'TUR', 'FW'),
    ('Matt Turner', 'USA', 'GK'),
    ('Sergiño Dest', 'USA', 'DF'),
    ('Chris Richards', 'USA', 'DF'),
    ('Tyler Adams', 'USA', 'MF'),
    ('Antonee Robinson', 'USA', 'DF'),
    ('Auston Trusty', 'USA', 'DF'),
    ('Giovanni Reyna', 'USA', 'MF'),
    ('Weston McKennie', 'USA', 'MF'),
    ('Ricardo Pepi', 'USA', 'FW'),
    ('Christian Pulisic', 'USA', 'FW'),
    ('Brenden Aaronson', 'USA', 'FW'),
    ('Miles Robinson', 'USA', 'DF'),
    ('Tim Ream', 'USA', 'DF'),
    ('Sebastian Berhalter', 'USA', 'MF'),
    ('Cristian Roldan', 'USA', 'MF'),
    ('Alex Freeman', 'USA', 'DF'),
    ('Malik Tillman', 'USA', 'MF'),
    ('Maximilian Arfsten', 'USA', 'DF'),
    ('Haji Wright', 'USA', 'FW'),
    ('Folarin Balogun', 'USA', 'FW'),
    ('Timothy Weah', 'USA', 'FW'),
    ('Mark McKenzie', 'USA', 'DF'),
    ('Joe Scally', 'USA', 'DF'),
    ('Matt Freese', 'USA', 'GK'),
    ('Chris Brady', 'USA', 'GK'),
    ('Alejandro Zendejas', 'USA', 'FW'),
    ('Eloy Room', 'CUW', 'GK'),
    ('Shurandy Sambo', 'CUW', 'DF'),
    ('Juriën Gaari', 'CUW', 'DF'),
    ('Roshon van Eijma', 'CUW', 'DF'),
    ('Sherel Floranus', 'CUW', 'DF'),
    ('Godfried Roemeratoe', 'CUW', 'MF'),
    ('Juninho Bacuna', 'CUW', 'MF'),
    ('Livano Comenencia', 'CUW', 'MF'),
    ('Jürgen Locadia', 'CUW', 'FW'),
    ('Leandro Bacuna', 'CUW', 'MF'),
    ('Jeremy Antonisse', 'CUW', 'FW'),
    ('Sontje Hansen', 'CUW', 'FW'),
    ('Tyrese Noslin', 'CUW', 'FW'),
    ('Kenji Gorré', 'CUW', 'FW'),
    ('Ar''jany Martha', 'CUW', 'MF'),
    ('Jearl Margaritha', 'CUW', 'FW'),
    ('Brandley Kuwas', 'CUW', 'FW'),
    ('Armando Obispo', 'CUW', 'DF'),
    ('Gervane Kastaneer', 'CUW', 'FW'),
    ('Joshua Brenet', 'CUW', 'DF'),
    ('Tahith Chong', 'CUW', 'MF'),
    ('Kevin Felida', 'CUW', 'MF'),
    ('Riechedly Bazoer', 'CUW', 'DF'),
    ('Deveron Fonville', 'CUW', 'DF'),
    ('Tyrick Bodak', 'CUW', 'GK'),
    ('Trevor Doornbusch', 'CUW', 'GK'),
    ('Hernán Galíndez', 'ECU', 'GK'),
    ('Félix Torres', 'ECU', 'DF'),
    ('Piero Hincapié', 'ECU', 'DF'),
    ('Joel Ordóñez', 'ECU', 'DF'),
    ('Jordy Alcívar', 'ECU', 'MF'),
    ('Willian Pacho', 'ECU', 'DF'),
    ('Pervis Estupiñán', 'ECU', 'DF'),
    ('Anthony Valencia', 'ECU', 'MF'),
    ('John Yeboah', 'ECU', 'FW'),
    ('Kendry Páez', 'ECU', 'MF'),
    ('Kevin Rodríguez', 'ECU', 'FW'),
    ('Moisés Ramírez', 'ECU', 'GK'),
    ('Enner Valencia', 'ECU', 'FW'),
    ('Alan Minda', 'ECU', 'MF'),
    ('Pedro Vite', 'ECU', 'MF'),
    ('Jordy Caicedo', 'ECU', 'FW'),
    ('Ángelo Preciado', 'ECU', 'DF'),
    ('Denil Castillo', 'ECU', 'MF'),
    ('Gonzalo Plata', 'ECU', 'FW'),
    ('Nilson Angulo', 'ECU', 'FW'),
    ('Alan Franco', 'ECU', 'MF'),
    ('Gonzalo Valle', 'ECU', 'GK'),
    ('Moisés Caicedo', 'ECU', 'MF'),
    ('Jeremy Arévalo', 'ECU', 'FW'),
    ('Jackson Porozo', 'ECU', 'DF'),
    ('Yaimar Medina', 'ECU', 'DF'),
    ('Manuel Neuer', 'GER', 'GK'),
    ('Antonio Rüdiger', 'GER', 'DF'),
    ('Waldemar Anton', 'GER', 'DF'),
    ('Jonathan Tah', 'GER', 'DF'),
    ('Aleksandar Pavlović', 'GER', 'MF'),
    ('Joshua Kimmich', 'GER', 'DF'),
    ('Kai Havertz', 'GER', 'FW'),
    ('Leon Goretzka', 'GER', 'MF'),
    ('Jamie Leweling', 'GER', 'MF'),
    ('Jamal Musiala', 'GER', 'MF'),
    ('Nick Woltemade', 'GER', 'FW'),
    ('Oliver Baumann', 'GER', 'GK'),
    ('Pascal Groß', 'GER', 'MF'),
    ('Maximilian Beier', 'GER', 'FW'),
    ('Nico Schlotterbeck', 'GER', 'DF'),
    ('Angelo Stiller', 'GER', 'MF'),
    ('Florian Wirtz', 'GER', 'MF'),
    ('Nathaniel Brown', 'GER', 'DF'),
    ('Leroy Sané', 'GER', 'MF'),
    ('Nadiem Amiri', 'GER', 'MF'),
    ('Alexander Nübel', 'GER', 'GK'),
    ('David Raum', 'GER', 'DF'),
    ('Felix Nmecha', 'GER', 'MF'),
    ('Malick Thiaw', 'GER', 'DF'),
    ('Lennart Karl', 'GER', 'MF'),
    ('Deniz Undav', 'GER', 'FW'),
    ('Yahia Fofana', 'CIV', 'GK'),
    ('Ousmane Diomande', 'CIV', 'DF'),
    ('Ghislain Konan', 'CIV', 'DF'),
    ('Jean Michaël Seri', 'CIV', 'MF'),
    ('Wilfried Singo', 'CIV', 'DF'),
    ('Seko Fofana', 'CIV', 'MF'),
    ('Odilon Kossounou', 'CIV', 'DF'),
    ('Franck Kessié', 'CIV', 'MF'),
    ('Ange-Yoan Bonny', 'CIV', 'FW'),
    ('Simon Adingra', 'CIV', 'FW'),
    ('Yan Diomande', 'CIV', 'FW'),
    ('Elye Wahi', 'CIV', 'FW'),
    ('Christopher Opéri', 'CIV', 'DF'),
    ('Oumar Diakité', 'CIV', 'FW'),
    ('Amad Diallo', 'CIV', 'FW'),
    ('Mohamed Koné', 'CIV', 'GK'),
    ('Guéla Doué', 'CIV', 'DF'),
    ('Ibrahim Sangaré', 'CIV', 'MF'),
    ('Nicolas Pépé', 'CIV', 'FW'),
    ('Emmanuel Agbadou', 'CIV', 'DF'),
    ('Evan Ndicka', 'CIV', 'DF'),
    ('Evann Guessand', 'CIV', 'FW'),
    ('Alban Lafont', 'CIV', 'GK'),
    ('Bazoumana Touré', 'CIV', 'FW'),
    ('Parfait Guiagon', 'CIV', 'MF'),
    ('Christ Inao Oulaï', 'CIV', 'MF'),
    ('Zion Suzuki', 'JPN', 'GK'),
    ('Yukinari Sugawara', 'JPN', 'DF'),
    ('Shōgo Taniguchi', 'JPN', 'DF'),
    ('Kō Itakura', 'JPN', 'DF'),
    ('Yūto Nagatomo', 'JPN', 'DF'),
    ('Wataru Endo', 'JPN', 'MF'),
    ('Ao Tanaka', 'JPN', 'MF'),
    ('Takefusa Kubo', 'JPN', 'MF'),
    ('Keisuke Gotō', 'JPN', 'FW'),
    ('Ritsu Dōan', 'JPN', 'MF'),
    ('Daizen Maeda', 'JPN', 'MF'),
    ('Keisuke Ōsako', 'JPN', 'GK'),
    ('Keito Nakamura', 'JPN', 'MF'),
    ('Junya Itō', 'JPN', 'MF'),
    ('Daichi Kamada', 'JPN', 'MF'),
    ('Tsuyoshi Watanabe', 'JPN', 'DF'),
    ('Yuito Suzuki', 'JPN', 'MF'),
    ('Ayase Ueda', 'JPN', 'FW'),
    ('Kōki Ogawa', 'JPN', 'FW'),
    ('Ayumu Seko', 'JPN', 'DF'),
    ('Hiroki Itō', 'JPN', 'DF'),
    ('Takehiro Tomiyasu', 'JPN', 'DF'),
    ('Tomoki Hayakawa', 'JPN', 'GK'),
    ('Kaishū Sano', 'JPN', 'MF'),
    ('Junnosuke Suzuki', 'JPN', 'DF'),
    ('Kento Shiogai', 'JPN', 'FW'),
    ('Bart Verbruggen', 'NED', 'GK'),
    ('Jurriën Timber', 'NED', 'DF'),
    ('Marten de Roon', 'NED', 'MF'),
    ('Virgil van Dijk', 'NED', 'DF'),
    ('Nathan Aké', 'NED', 'DF'),
    ('Jan Paul van Hecke', 'NED', 'DF'),
    ('Justin Kluivert', 'NED', 'MF'),
    ('Ryan Gravenberch', 'NED', 'MF'),
    ('Wout Weghorst', 'NED', 'FW'),
    ('Memphis Depay', 'NED', 'FW'),
    ('Cody Gakpo', 'NED', 'FW'),
    ('Mats Wieffer', 'NED', 'DF'),
    ('Robin Roefs', 'NED', 'GK'),
    ('Tijjani Reijnders', 'NED', 'MF'),
    ('Micky van de Ven', 'NED', 'DF'),
    ('Guus Til', 'NED', 'MF'),
    ('Noa Lang', 'NED', 'FW'),
    ('Donyell Malen', 'NED', 'FW'),
    ('Brian Brobbey', 'NED', 'FW'),
    ('Teun Koopmeiners', 'NED', 'MF'),
    ('Frenkie de Jong', 'NED', 'MF'),
    ('Denzel Dumfries', 'NED', 'DF'),
    ('Mark Flekken', 'NED', 'GK'),
    ('Crysencio Summerville', 'NED', 'FW'),
    ('Jorrel Hato', 'NED', 'DF'),
    ('Quinten Timber', 'NED', 'MF'),
    ('Jacob Widell Zetterström', 'SWE', 'GK'),
    ('Gustaf Lagerbielke', 'SWE', 'DF'),
    ('Victor Lindelöf', 'SWE', 'DF'),
    ('Isak Hien', 'SWE', 'DF'),
    ('Gabriel Gudmundsson', 'SWE', 'DF'),
    ('Herman Johansson', 'SWE', 'DF'),
    ('Lucas Bergvall', 'SWE', 'MF'),
    ('Daniel Svensson', 'SWE', 'DF'),
    ('Alexander Isak', 'SWE', 'FW'),
    ('Benjamin Nygren', 'SWE', 'MF'),
    ('Anthony Elanga', 'SWE', 'FW'),
    ('Viktor Johansson', 'SWE', 'GK'),
    ('Ken Sema', 'SWE', 'MF'),
    ('Hjalmar Ekdal', 'SWE', 'DF'),
    ('Carl Starfelt', 'SWE', 'DF'),
    ('Jesper Karlström', 'SWE', 'MF'),
    ('Viktor Gyökeres', 'SWE', 'FW'),
    ('Yasin Ayari', 'SWE', 'MF'),
    ('Mattias Svanberg', 'SWE', 'MF'),
    ('Eric Smith', 'SWE', 'DF'),
    ('Alexander Bernhardsson', 'SWE', 'DF'),
    ('Besfort Zeneli', 'SWE', 'MF'),
    ('Kristoffer Nordfeldt', 'SWE', 'GK'),
    ('Elliot Stroud', 'SWE', 'DF'),
    ('Gustaf Nilsson', 'SWE', 'FW'),
    ('Taha Ali', 'SWE', 'FW'),
    ('Mouhib Chamakh', 'TUN', 'GK'),
    ('Ali Abdi', 'TUN', 'DF'),
    ('Montassar Talbi', 'TUN', 'DF'),
    ('Omar Rekik', 'TUN', 'DF'),
    ('Adem Arous', 'TUN', 'DF'),
    ('Dylan Bronn', 'TUN', 'DF'),
    ('Elias Achouri', 'TUN', 'FW'),
    ('Elias Saad', 'TUN', 'FW'),
    ('Hazem Mastouri', 'TUN', 'FW'),
    ('Hannibal Mejbri', 'TUN', 'MF'),
    ('Ismaël Gharbi', 'TUN', 'MF'),
    ('Mortadha Ben Ouanes', 'TUN', 'DF'),
    ('Rani Khedira', 'TUN', 'MF'),
    ('Khalil Ayari', 'TUN', 'MF'),
    ('Hadj Mahmoud', 'TUN', 'MF'),
    ('Aymen Dahmen', 'TUN', 'GK'),
    ('Ellyes Skhiri', 'TUN', 'MF'),
    ('Rayan Elloumi', 'TUN', 'FW'),
    ('Firas Chaouat', 'TUN', 'FW'),
    ('Yan Valery', 'TUN', 'DF'),
    ('Mohamed Amine Ben Hamida', 'TUN', 'DF'),
    ('Sabri Ben Hessen', 'TUN', 'GK'),
    ('Moutaz Neffati', 'TUN', 'DF'),
    ('Raed Chikhaoui', 'TUN', 'DF'),
    ('Anis Ben Slimane', 'TUN', 'MF'),
    ('Sebastian Tounekti', 'TUN', 'MF'),
    ('Thibaut Courtois', 'BEL', 'GK'),
    ('Zeno Debast', 'BEL', 'DF'),
    ('Arthur Theate', 'BEL', 'DF'),
    ('Brandon Mechele', 'BEL', 'DF'),
    ('Maxim De Cuyper', 'BEL', 'DF'),
    ('Axel Witsel', 'BEL', 'MF'),
    ('Kevin De Bruyne', 'BEL', 'MF'),
    ('Youri Tielemans', 'BEL', 'MF'),
    ('Romelu Lukaku', 'BEL', 'FW'),
    ('Leandro Trossard', 'BEL', 'FW'),
    ('Jérémy Doku', 'BEL', 'FW'),
    ('Senne Lammens', 'BEL', 'GK'),
    ('Mike Penders', 'BEL', 'GK'),
    ('Dodi Lukébakio', 'BEL', 'FW'),
    ('Thomas Meunier', 'BEL', 'DF'),
    ('Koni De Winter', 'BEL', 'DF'),
    ('Charles De Ketelaere', 'BEL', 'FW'),
    ('Joaquin Seys', 'BEL', 'DF'),
    ('Diego Moreira', 'BEL', 'MF'),
    ('Hans Vanaken', 'BEL', 'MF'),
    ('Timothy Castagne', 'BEL', 'DF'),
    ('Alexis Saelemaekers', 'BEL', 'MF'),
    ('Nicolas Raskin', 'BEL', 'MF'),
    ('Amadou Onana', 'BEL', 'MF'),
    ('Nathan Ngoy', 'BEL', 'DF'),
    ('Matias Fernandez-Pardo', 'BEL', 'FW'),
    ('Mohamed El Shenawy', 'EGY', 'GK'),
    ('Yasser Ibrahim', 'EGY', 'DF'),
    ('Mohamed Hany', 'EGY', 'DF'),
    ('Hossam Abdelmaguid', 'EGY', 'DF'),
    ('Ramy Rabia', 'EGY', 'DF'),
    ('Mohamed Abdelmonem', 'EGY', 'DF'),
    ('Trézéguet', 'EGY', 'FW'),
    ('Emam Ashour', 'EGY', 'MF'),
    ('Hamza Abdelkarim', 'EGY', 'FW'),
    ('Mohamed Salah', 'EGY', 'FW'),
    ('Mostafa Ziko', 'EGY', 'MF'),
    ('Haissem Hassan', 'EGY', 'FW'),
    ('Ahmed Fatouh', 'EGY', 'DF'),
    ('Hamdy Fathy', 'EGY', 'MF'),
    ('Karim Hafez', 'EGY', 'DF'),
    ('El Mahdy Soliman', 'EGY', 'GK'),
    ('Mohanad Lasheen', 'EGY', 'MF'),
    ('Nabil Emad', 'EGY', 'MF'),
    ('Marwan Attia', 'EGY', 'MF'),
    ('Ibrahim Adel', 'EGY', 'FW'),
    ('Mahmoud Saber', 'EGY', 'MF'),
    ('Omar Marmoush', 'EGY', 'FW'),
    ('Mostafa Shobeir', 'EGY', 'GK'),
    ('Tarek Alaa', 'EGY', 'DF'),
    ('Zizo', 'EGY', 'FW'),
    ('Mohamed Alaa', 'EGY', 'GK'),
    ('Alireza Beiranvand', 'IRN', 'GK'),
    ('Saleh Hardani', 'IRN', 'DF'),
    ('Ehsan Hajsafi', 'IRN', 'DF'),
    ('Shojae Khalilzadeh', 'IRN', 'DF'),
    ('Milad Mohammadi', 'IRN', 'DF'),
    ('Saeid Ezatolahi', 'IRN', 'MF'),
    ('Alireza Jahanbakhsh', 'IRN', 'MF'),
    ('Mohammad Mohebi', 'IRN', 'MF'),
    ('Mehdi Taremi', 'IRN', 'FW'),
    ('Mehdi Ghayedi', 'IRN', 'FW'),
    ('Ali Alipour', 'IRN', 'FW'),
    ('Payam Niazmand', 'IRN', 'GK'),
    ('Hossein Kanaanizadegan', 'IRN', 'DF'),
    ('Saman Ghoddos', 'IRN', 'MF'),
    ('Rouzbeh Cheshmi', 'IRN', 'MF'),
    ('Mehdi Torabi', 'IRN', 'MF'),
    ('Aria Yousefi', 'IRN', 'DF'),
    ('Amirhossein Hosseinzadeh', 'IRN', 'FW'),
    ('Ali Nemati', 'IRN', 'DF'),
    ('Shahriyar Moghanlou', 'IRN', 'FW'),
    ('Mohammad Ghorbani', 'IRN', 'MF'),
    ('Hossein Hosseini', 'IRN', 'GK'),
    ('Ramin Rezaeian', 'IRN', 'DF'),
    ('Dennis Eckert', 'IRN', 'FW'),
    ('Danial Eiri', 'IRN', 'DF'),
    ('Amirmohammad Razzaghinia', 'IRN', 'MF'),
    ('Max Crocombe', 'NZL', 'GK'),
    ('Tim Payne', 'NZL', 'DF'),
    ('Francis de Vries', 'NZL', 'DF'),
    ('Tyler Bindon', 'NZL', 'DF'),
    ('Michael Boxall', 'NZL', 'DF'),
    ('Joe Bell', 'NZL', 'MF'),
    ('Matthew Garbett', 'NZL', 'MF'),
    ('Marko Stamenić', 'NZL', 'MF'),
    ('Chris Wood', 'NZL', 'FW'),
    ('Sarpreet Singh', 'NZL', 'MF'),
    ('Elijah Just', 'NZL', 'MF'),
    ('Alex Paulsen', 'NZL', 'GK'),
    ('Liberato Cacace', 'NZL', 'DF'),
    ('Alex Rufer', 'NZL', 'MF'),
    ('Nando Pijnaker', 'NZL', 'DF'),
    ('Finn Surman', 'NZL', 'DF'),
    ('Kosta Barbarouses', 'NZL', 'FW'),
    ('Ben Waine', 'NZL', 'FW'),
    ('Ben Old', 'NZL', 'MF'),
    ('Callum McCowatt', 'NZL', 'MF'),
    ('Jesse Randall', 'NZL', 'FW'),
    ('Michael Woud', 'NZL', 'GK'),
    ('Ryan Thomas', 'NZL', 'MF'),
    ('Callan Elliot', 'NZL', 'DF'),
    ('Lachlan Bayliss', 'NZL', 'MF'),
    ('Tommy Smith', 'NZL', 'DF'),
    ('Vozinha', 'CPV', 'GK'),
    ('Stopira', 'CPV', 'DF'),
    ('Diney', 'CPV', 'DF'),
    ('Roberto Lopes', 'CPV', 'DF'),
    ('Logan Costa', 'CPV', 'DF'),
    ('Kevin Pina', 'CPV', 'MF'),
    ('Jovane Cabral', 'CPV', 'MF'),
    ('João Paulo', 'CPV', 'MF'),
    ('Gilson Benchimol', 'CPV', 'FW'),
    ('Jamiro Monteiro', 'CPV', 'MF'),
    ('Garry Rodrigues', 'CPV', 'MF'),
    ('Márcio Rosa', 'CPV', 'GK'),
    ('Sidny Lopes Cabral', 'CPV', 'DF'),
    ('Deroy Duarte', 'CPV', 'MF'),
    ('Laros Duarte', 'CPV', 'MF'),
    ('Yannick Semedo', 'CPV', 'MF'),
    ('Willy Semedo', 'CPV', 'MF'),
    ('Telmo Arcanjo', 'CPV', 'MF'),
    ('Dailon Livramento', 'CPV', 'FW'),
    ('Ryan Mendes', 'CPV', 'FW'),
    ('Nuno da Costa', 'CPV', 'MF'),
    ('Steven Moreira', 'CPV', 'DF'),
    ('CJ dos Santos', 'CPV', 'GK'),
    ('Wagner Pina', 'CPV', 'DF'),
    ('Kelvin Pires', 'CPV', 'DF'),
    ('Hélio Varela', 'CPV', 'MF'),
    ('Nawaf Al-Aqidi', 'KSA', 'GK'),
    ('Ali Majrashi', 'KSA', 'DF'),
    ('Ali Lajami', 'KSA', 'DF'),
    ('Abdulelah Al-Amri', 'KSA', 'DF'),
    ('Hassan Al-Tambakti', 'KSA', 'DF'),
    ('Nasser Al-Dawsari', 'KSA', 'MF'),
    ('Musab Al-Juwayr', 'KSA', 'MF'),
    ('Ayman Yahya', 'KSA', 'FW'),
    ('Firas Al-Buraikan', 'KSA', 'FW'),
    ('Salem Al-Dawsari', 'KSA', 'FW'),
    ('Saleh Al-Shehri', 'KSA', 'FW'),
    ('Saud Abdulhamid', 'KSA', 'DF'),
    ('Nawaf Boushal', 'KSA', 'DF'),
    ('Hassan Kadesh', 'KSA', 'DF'),
    ('Abdullah Al-Khaibari', 'KSA', 'MF'),
    ('Ziyad Al-Johani', 'KSA', 'MF'),
    ('Khalid Al-Ghannam', 'KSA', 'FW'),
    ('Alaa Al-Hejji', 'KSA', 'MF'),
    ('Abdullah Al-Hamdan', 'KSA', 'FW'),
    ('Sultan Mandash', 'KSA', 'FW'),
    ('Mohammed Al-Owais', 'KSA', 'GK'),
    ('Ahmed Al-Kassar', 'KSA', 'GK'),
    ('Mohamed Kanno', 'KSA', 'MF'),
    ('Moteb Al-Harbi', 'KSA', 'DF'),
    ('Jehad Thakri', 'KSA', 'DF'),
    ('Mohammed Abu Al-Shamat', 'KSA', 'DF'),
    ('David Raya', 'ESP', 'GK'),
    ('Marc Pubill', 'ESP', 'DF'),
    ('Álex Grimaldo', 'ESP', 'DF'),
    ('Eric García', 'ESP', 'DF'),
    ('Marcos Llorente', 'ESP', 'DF'),
    ('Mikel Merino', 'ESP', 'MF'),
    ('Ferran Torres', 'ESP', 'FW'),
    ('Fabián Ruiz', 'ESP', 'MF'),
    ('Gavi', 'ESP', 'MF'),
    ('Dani Olmo', 'ESP', 'FW'),
    ('Yéremy Pino', 'ESP', 'FW'),
    ('Pedro Porro', 'ESP', 'DF'),
    ('Joan Garcia', 'ESP', 'GK'),
    ('Aymeric Laporte', 'ESP', 'DF'),
    ('Álex Baena', 'ESP', 'MF'),
    ('Rodri', 'ESP', 'MF'),
    ('Nico Williams', 'ESP', 'FW'),
    ('Martín Zubimendi', 'ESP', 'MF'),
    ('Lamine Yamal', 'ESP', 'FW'),
    ('Pedri', 'ESP', 'MF'),
    ('Mikel Oyarzabal', 'ESP', 'FW'),
    ('Pau Cubarsí', 'ESP', 'DF'),
    ('Unai Simón', 'ESP', 'GK'),
    ('Marc Cucurella', 'ESP', 'DF'),
    ('Víctor Muñoz', 'ESP', 'FW'),
    ('Borja Iglesias', 'ESP', 'FW'),
    ('Sergio Rochet', 'URU', 'GK'),
    ('José María Giménez', 'URU', 'DF'),
    ('Sebastián Cáceres', 'URU', 'DF'),
    ('Ronald Araújo', 'URU', 'DF'),
    ('Manuel Ugarte', 'URU', 'MF'),
    ('Rodrigo Bentancur', 'URU', 'MF'),
    ('Nicolás de la Cruz', 'URU', 'MF'),
    ('Federico Valverde', 'URU', 'MF'),
    ('Darwin Núñez', 'URU', 'FW'),
    ('Giorgian de Arrascaeta', 'URU', 'MF'),
    ('Facundo Pellistri', 'URU', 'FW'),
    ('Santiago Mele', 'URU', 'GK'),
    ('Guillermo Varela', 'URU', 'DF'),
    ('Agustín Canobbio', 'URU', 'MF'),
    ('Emiliano Martínez', 'URU', 'MF'),
    ('Mathías Olivera', 'URU', 'DF'),
    ('Matías Viña', 'URU', 'DF'),
    ('Brian Rodríguez', 'URU', 'FW'),
    ('Rodrigo Aguirre', 'URU', 'FW'),
    ('Maximiliano Araújo', 'URU', 'MF'),
    ('Federico Viñas', 'URU', 'FW'),
    ('Joaquín Piquerez', 'URU', 'MF'),
    ('Fernando Muslera', 'URU', 'GK'),
    ('Santiago Bueno', 'URU', 'DF'),
    ('Juan Manuel Sanabria', 'URU', 'MF'),
    ('Rodrigo Zalazar', 'URU', 'MF'),
    ('Brice Samba', 'FRA', 'GK'),
    ('Malo Gusto', 'FRA', 'DF'),
    ('Lucas Digne', 'FRA', 'DF'),
    ('Dayot Upamecano', 'FRA', 'DF'),
    ('Jules Koundé', 'FRA', 'DF'),
    ('Manu Koné', 'FRA', 'MF'),
    ('Ousmane Dembélé', 'FRA', 'FW'),
    ('Aurélien Tchouaméni', 'FRA', 'MF'),
    ('Marcus Thuram', 'FRA', 'FW'),
    ('Kylian Mbappé', 'FRA', 'FW'),
    ('Michael Olise', 'FRA', 'FW'),
    ('Bradley Barcola', 'FRA', 'FW'),
    ('N''Golo Kanté', 'FRA', 'MF'),
    ('Adrien Rabiot', 'FRA', 'MF'),
    ('Ibrahima Konaté', 'FRA', 'DF'),
    ('Mike Maignan', 'FRA', 'GK'),
    ('William Saliba', 'FRA', 'DF'),
    ('Warren Zaïre-Emery', 'FRA', 'MF'),
    ('Théo Hernandez', 'FRA', 'DF'),
    ('Désiré Doué', 'FRA', 'FW'),
    ('Lucas Hernandez', 'FRA', 'DF'),
    ('Jean-Philippe Mateta', 'FRA', 'FW'),
    ('Robin Risser', 'FRA', 'GK'),
    ('Rayan Cherki', 'FRA', 'MF'),
    ('Maghnes Akliouche', 'FRA', 'MF'),
    ('Maxence Lacroix', 'FRA', 'DF'),
    ('Fahad Talib', 'IRQ', 'GK'),
    ('Rebin Sulaka', 'IRQ', 'DF'),
    ('Hussein Ali', 'IRQ', 'DF'),
    ('Zaid Tahseen', 'IRQ', 'DF'),
    ('Akam Hashim', 'IRQ', 'DF'),
    ('Manaf Younis', 'IRQ', 'DF'),
    ('Youssef Amyn', 'IRQ', 'MF'),
    ('Ibrahim Bayesh', 'IRQ', 'MF'),
    ('Ali Al-Hamadi', 'IRQ', 'FW'),
    ('Mohanad Ali', 'IRQ', 'FW'),
    ('Ahmed Qasem', 'IRQ', 'FW'),
    ('Jalal Hassan', 'IRQ', 'GK'),
    ('Ali Yousif', 'IRQ', 'FW'),
    ('Zidane Iqbal', 'IRQ', 'MF'),
    ('Ahmed Yahya', 'IRQ', 'DF'),
    ('Amir Al-Ammari', 'IRQ', 'MF'),
    ('Ali Jasim', 'IRQ', 'FW'),
    ('Aymen Hussein', 'IRQ', 'FW'),
    ('Kevin Yakob', 'IRQ', 'MF'),
    ('Aimar Sher', 'IRQ', 'MF'),
    ('Marko Farji', 'IRQ', 'FW'),
    ('Ahmed Basil', 'IRQ', 'GK'),
    ('Merchas Doski', 'IRQ', 'DF'),
    ('Zaid Ismail', 'IRQ', 'MF'),
    ('Mustafa Saadoon', 'IRQ', 'DF'),
    ('Frans Putros', 'IRQ', 'DF'),
    ('Ørjan Nyland', 'NOR', 'GK'),
    ('Morten Thorsby', 'NOR', 'MF'),
    ('Kristoffer Ajer', 'NOR', 'DF'),
    ('Leo Østigård', 'NOR', 'DF'),
    ('David Møller Wolfe', 'NOR', 'DF'),
    ('Patrick Berg', 'NOR', 'MF'),
    ('Alexander Sørloth', 'NOR', 'FW'),
    ('Sander Berge', 'NOR', 'MF'),
    ('Erling Haaland', 'NOR', 'FW'),
    ('Martin Ødegaard', 'NOR', 'MF'),
    ('Jørgen Strand Larsen', 'NOR', 'FW'),
    ('Sander Tangvik', 'NOR', 'GK'),
    ('Egil Selvik', 'NOR', 'GK'),
    ('Fredrik Aursnes', 'NOR', 'MF'),
    ('Fredrik André Bjørkan', 'NOR', 'DF'),
    ('Marcus Holmgren Pedersen', 'NOR', 'DF'),
    ('Torbjørn Heggem', 'NOR', 'DF'),
    ('Kristian Thorstvedt', 'NOR', 'MF'),
    ('Thelo Aasgaard', 'NOR', 'MF'),
    ('Antonio Nusa', 'NOR', 'FW'),
    ('Andreas Schjelderup', 'NOR', 'MF'),
    ('Oscar Bobb', 'NOR', 'MF'),
    ('Jens Petter Hauge', 'NOR', 'MF'),
    ('Sondre Langås', 'NOR', 'DF'),
    ('Henrik Falchener', 'NOR', 'DF'),
    ('Julian Ryerson', 'NOR', 'FW'),
    ('Yehvann Diouf', 'SEN', 'GK'),
    ('Mamadou Sarr', 'SEN', 'DF'),
    ('Kalidou Koulibaly', 'SEN', 'DF'),
    ('Abdoulaye Seck', 'SEN', 'DF'),
    ('Idrissa Gueye', 'SEN', 'MF'),
    ('Pathé Ciss', 'SEN', 'MF'),
    ('Assane Diao', 'SEN', 'FW'),
    ('Lamine Camara', 'SEN', 'MF'),
    ('Bamba Dieng', 'SEN', 'FW'),
    ('Sadio Mané', 'SEN', 'FW'),
    ('Nicolas Jackson', 'SEN', 'FW'),
    ('Cherif Ndiaye', 'SEN', 'FW'),
    ('Iliman Ndiaye', 'SEN', 'FW'),
    ('Ismail Jakobs', 'SEN', 'DF'),
    ('Krépin Diatta', 'SEN', 'DF'),
    ('Édouard Mendy', 'SEN', 'GK'),
    ('Pape Matar Sarr', 'SEN', 'MF'),
    ('Ismaïla Sarr', 'SEN', 'FW'),
    ('Moussa Niakhaté', 'SEN', 'DF'),
    ('Ibrahim Mbaye', 'SEN', 'FW'),
    ('Habib Diarra', 'SEN', 'MF'),
    ('Bara Sapoko Ndiaye', 'SEN', 'MF'),
    ('Mory Diaw', 'SEN', 'GK'),
    ('Antoine Mendy', 'SEN', 'DF'),
    ('El Hadji Malick Diouf', 'SEN', 'DF'),
    ('Pape Gueye', 'SEN', 'MF'),
    ('Melvin Mastil', 'ALG', 'GK'),
    ('Aïssa Mandi', 'ALG', 'DF'),
    ('Achref Abada', 'ALG', 'DF'),
    ('Mohamed Amine Tougai', 'ALG', 'DF'),
    ('Zineddine Belaïd', 'ALG', 'DF'),
    ('Ramiz Zerrouki', 'ALG', 'MF'),
    ('Riyad Mahrez', 'ALG', 'FW'),
    ('Houssem Aouar', 'ALG', 'MF'),
    ('Amine Gouiri', 'ALG', 'FW'),
    ('Farès Chaïbi', 'ALG', 'MF'),
    ('Anis Hadj Moussa', 'ALG', 'FW'),
    ('Nadhir Benbouali', 'ALG', 'FW'),
    ('Jaouen Hadjam', 'ALG', 'DF'),
    ('Hicham Boudaoui', 'ALG', 'MF'),
    ('Rayan Aït-Nouri', 'ALG', 'DF'),
    ('Oussama Benbot', 'ALG', 'GK'),
    ('Rafik Belghali', 'ALG', 'DF'),
    ('Mohamed Amoura', 'ALG', 'FW'),
    ('Nabil Bentaleb', 'ALG', 'MF'),
    ('Adil Boulbina', 'ALG', 'FW'),
    ('Ramy Bensebaini', 'ALG', 'DF'),
    ('Ibrahim Maza', 'ALG', 'MF'),
    ('Luca Zidane', 'ALG', 'GK'),
    ('Yacine Titraoui', 'ALG', 'MF'),
    ('Farès Ghedjemis', 'ALG', 'FW'),
    ('Samir Chergui', 'ALG', 'DF'),
    ('Juan Musso', 'ARG', 'GK'),
    ('Leonardo Balerdi', 'ARG', 'DF'),
    ('Nicolás Tagliafico', 'ARG', 'DF'),
    ('Gonzalo Montiel', 'ARG', 'DF'),
    ('Leandro Paredes', 'ARG', 'MF'),
    ('Lisandro Martínez', 'ARG', 'DF'),
    ('Rodrigo De Paul', 'ARG', 'MF'),
    ('Valentín Barco', 'ARG', 'MF'),
    ('Julián Alvarez', 'ARG', 'FW'),
    ('Lionel Messi', 'ARG', 'FW'),
    ('Giovani Lo Celso', 'ARG', 'MF'),
    ('Gerónimo Rulli', 'ARG', 'GK'),
    ('Cristian Romero', 'ARG', 'DF'),
    ('Exequiel Palacios', 'ARG', 'MF'),
    ('Nicolás González', 'ARG', 'MF'),
    ('Thiago Almada', 'ARG', 'FW'),
    ('Giuliano Simeone', 'ARG', 'FW'),
    ('Nico Paz', 'ARG', 'FW'),
    ('Nicolás Otamendi', 'ARG', 'DF'),
    ('Alexis Mac Allister', 'ARG', 'MF'),
    ('José Manuel López', 'ARG', 'FW'),
    ('Lautaro Martínez', 'ARG', 'FW'),
    ('Emiliano Martínez', 'ARG', 'GK'),
    ('Enzo Fernández', 'ARG', 'MF'),
    ('Facundo Medina', 'ARG', 'DF'),
    ('Nahuel Molina', 'ARG', 'DF'),
    ('Alexander Schlager', 'AUT', 'GK'),
    ('David Affengruber', 'AUT', 'DF'),
    ('Kevin Danso', 'AUT', 'DF'),
    ('Xaver Schlager', 'AUT', 'MF'),
    ('Stefan Posch', 'AUT', 'DF'),
    ('Nicolas Seiwald', 'AUT', 'MF'),
    ('Marko Arnautović', 'AUT', 'FW'),
    ('David Alaba', 'AUT', 'DF'),
    ('Marcel Sabitzer', 'AUT', 'MF'),
    ('Florian Grillitsch', 'AUT', 'MF'),
    ('Michael Gregoritsch', 'AUT', 'FW'),
    ('Florian Wiegele', 'AUT', 'GK'),
    ('Patrick Pentz', 'AUT', 'GK'),
    ('Saša Kalajdžić', 'AUT', 'FW'),
    ('Philipp Lienhart', 'AUT', 'DF'),
    ('Phillipp Mwene', 'AUT', 'DF'),
    ('Carney Chukwuemeka', 'AUT', 'MF'),
    ('Romano Schmid', 'AUT', 'MF'),
    ('Christoph Baumgartner', 'AUT', 'MF'),
    ('Konrad Laimer', 'AUT', 'MF'),
    ('Patrick Wimmer', 'AUT', 'FW'),
    ('Alexander Prass', 'AUT', 'MF'),
    ('Marco Friedl', 'AUT', 'DF'),
    ('Paul Wanner', 'AUT', 'MF'),
    ('Michael Svoboda', 'AUT', 'DF'),
    ('Alessandro Schöpf', 'AUT', 'MF'),
    ('Yazeed Abulaila', 'JOR', 'GK'),
    ('Mohammad Abu Hashish', 'JOR', 'DF'),
    ('Abdallah Nasib', 'JOR', 'DF'),
    ('Husam Abu Dahab', 'JOR', 'DF'),
    ('Yazan Al-Arab', 'JOR', 'DF'),
    ('Amer Jamous', 'JOR', 'MF'),
    ('Mohammad Abu Zrayq', 'JOR', 'FW'),
    ('Noor Al-Rawabdeh', 'JOR', 'MF'),
    ('Ali Olwan', 'JOR', 'FW'),
    ('Musa Al-Taamari', 'JOR', 'FW'),
    ('Odeh Al-Fakhouri', 'JOR', 'FW'),
    ('Nour Bani Attiah', 'JOR', 'GK'),
    ('Mahmoud Al-Mardi', 'JOR', 'FW'),
    ('Rajaei Ayed', 'JOR', 'MF'),
    ('Ibrahim Sadeh', 'JOR', 'MF'),
    ('Mo Abualnadi', 'JOR', 'DF'),
    ('Salim Obaid', 'JOR', 'DF'),
    ('Ibrahim Sabra', 'JOR', 'FW'),
    ('Saed Al-Rosan', 'JOR', 'DF'),
    ('Mohannad Abu Taha', 'JOR', 'MF'),
    ('Nizar Al-Rashdan', 'JOR', 'MF'),
    ('Abdallah Al-Fakhouri', 'JOR', 'GK'),
    ('Ihsan Haddad', 'JOR', 'DF'),
    ('Ali Azaizeh', 'JOR', 'FW'),
    ('Mohammad Al-Dawoud', 'JOR', 'MF'),
    ('Anas Badawi', 'JOR', 'DF'),
    ('David Ospina', 'COL', 'GK'),
    ('Daniel Muñoz', 'COL', 'DF'),
    ('Jhon Lucumí', 'COL', 'DF'),
    ('Santiago Arias', 'COL', 'DF'),
    ('Kevin Castaño', 'COL', 'MF'),
    ('Richard Ríos', 'COL', 'MF'),
    ('Luis Díaz', 'COL', 'FW'),
    ('Jorge Carrascal', 'COL', 'MF'),
    ('Jhon Córdoba', 'COL', 'FW'),
    ('James Rodríguez', 'COL', 'MF'),
    ('Jhon Arias', 'COL', 'MF'),
    ('Camilo Vargas', 'COL', 'GK'),
    ('Yerry Mina', 'COL', 'DF'),
    ('Gustavo Puerta', 'COL', 'DF'),
    ('Juan Portilla', 'COL', 'MF'),
    ('Jefferson Lerma', 'COL', 'MF'),
    ('Johan Mojica', 'COL', 'DF'),
    ('Willer Ditta', 'COL', 'DF'),
    ('Cucho Hernández', 'COL', 'FW'),
    ('Juan Fernando Quintero', 'COL', 'MF'),
    ('Jaminton Campaz', 'COL', 'FW'),
    ('Deiver Machado', 'COL', 'DF'),
    ('Davinson Sánchez', 'COL', 'DF'),
    ('Álvaro Montero', 'COL', 'GK'),
    ('Luis Suárez', 'COL', 'FW'),
    ('Andrés Gómez', 'COL', 'FW'),
    ('Lionel Mpasi', 'COD', 'GK'),
    ('Aaron Wan-Bissaka', 'COD', 'DF'),
    ('Steve Kapuadi', 'COD', 'DF'),
    ('Axel Tuanzebe', 'COD', 'DF'),
    ('Dylan Batubinsika', 'COD', 'DF'),
    ('Ngal''ayel Mukau', 'COD', 'MF'),
    ('Nathanaël Mbuku', 'COD', 'MF'),
    ('Samuel Moutoussamy', 'COD', 'MF'),
    ('Brian Cipenga', 'COD', 'FW'),
    ('Théo Bongonda', 'COD', 'MF'),
    ('Gaël Kakuta', 'COD', 'FW'),
    ('Joris Kayembe', 'COD', 'DF'),
    ('Meschak Elia', 'COD', 'FW'),
    ('Noah Sadiki', 'COD', 'MF'),
    ('Aaron Tshibola', 'COD', 'MF'),
    ('Timothy Fayulu', 'COD', 'GK'),
    ('Cédric Bakambu', 'COD', 'FW'),
    ('Charles Pickel', 'COD', 'MF'),
    ('Fiston Mayele', 'COD', 'FW'),
    ('Yoane Wissa', 'COD', 'FW'),
    ('Matthieu Epolo', 'COD', 'GK'),
    ('Chancel Mbemba', 'COD', 'DF'),
    ('Simon Banza', 'COD', 'FW'),
    ('Gédéon Kalulu', 'COD', 'DF'),
    ('Edo Kayembe', 'COD', 'MF'),
    ('Arthur Masuaku', 'COD', 'DF'),
    ('Diogo Costa', 'POR', 'GK'),
    ('Nélson Semedo', 'POR', 'DF'),
    ('Rúben Dias', 'POR', 'DF'),
    ('Tomás Araújo', 'POR', 'DF'),
    ('Diogo Dalot', 'POR', 'DF'),
    ('Matheus Nunes', 'POR', 'MF'),
    ('Cristiano Ronaldo', 'POR', 'FW'),
    ('Bruno Fernandes', 'POR', 'MF'),
    ('Gonçalo Ramos', 'POR', 'FW'),
    ('Bernardo Silva', 'POR', 'MF'),
    ('João Félix', 'POR', 'FW'),
    ('José Sá', 'POR', 'GK'),
    ('Renato Veiga', 'POR', 'DF'),
    ('Gonçalo Inácio', 'POR', 'DF'),
    ('João Neves', 'POR', 'MF'),
    ('Francisco Trincão', 'POR', 'FW'),
    ('Rafael Leão', 'POR', 'FW'),
    ('Pedro Neto', 'POR', 'FW'),
    ('Gonçalo Guedes', 'POR', 'FW'),
    ('João Cancelo', 'POR', 'DF'),
    ('Rúben Neves', 'POR', 'MF'),
    ('Rui Silva', 'POR', 'GK'),
    ('Vitinha', 'POR', 'MF'),
    ('Samú Costa', 'POR', 'DF'),
    ('Nuno Mendes', 'POR', 'DF'),
    ('Francisco Conceição', 'POR', 'FW'),
    ('Utkir Yusupov', 'UZB', 'GK'),
    ('Abdukodir Khusanov', 'UZB', 'DF'),
    ('Khojiakbar Alijonov', 'UZB', 'DF'),
    ('Farrukh Sayfiev', 'UZB', 'DF'),
    ('Rustam Ashurmatov', 'UZB', 'DF'),
    ('Akmal Mozgovoy', 'UZB', 'MF'),
    ('Otabek Shukurov', 'UZB', 'MF'),
    ('Jamshid Iskanderov', 'UZB', 'MF'),
    ('Odiljon Hamrobekov', 'UZB', 'MF'),
    ('Jaloliddin Masharipov', 'UZB', 'MF'),
    ('Oston Urunov', 'UZB', 'MF'),
    ('Abduvohid Nematov', 'UZB', 'GK'),
    ('Sherzod Nasrullaev', 'UZB', 'DF'),
    ('Eldor Shomurodov', 'UZB', 'FW'),
    ('Umar Eshmurodov', 'UZB', 'DF'),
    ('Botirali Ergashev', 'UZB', 'GK'),
    ('Dostonbek Khamdamov', 'UZB', 'MF'),
    ('Abdulla Abdullaev', 'UZB', 'DF'),
    ('Azizjon Ganiev', 'UZB', 'MF'),
    ('Azizbek Amonov', 'UZB', 'FW'),
    ('Igor Sergeev', 'UZB', 'FW'),
    ('Abbosbek Fayzullaev', 'UZB', 'MF'),
    ('Sherzod Esanov', 'UZB', 'MF'),
    ('Bekhruz Karimov', 'UZB', 'DF'),
    ('Avazbek Ulmasaliev', 'UZB', 'DF'),
    ('Jakhongir Urozov', 'UZB', 'DF'),
    ('Dominik Livaković', 'CRO', 'GK'),
    ('Josip Stanišić', 'CRO', 'DF'),
    ('Marin Pongračić', 'CRO', 'DF'),
    ('Joško Gvardiol', 'CRO', 'DF'),
    ('Duje Ćaleta-Car', 'CRO', 'DF'),
    ('Josip Šutalo', 'CRO', 'DF'),
    ('Nikola Moro', 'CRO', 'MF'),
    ('Mateo Kovačić', 'CRO', 'MF'),
    ('Andrej Kramarić', 'CRO', 'FW'),
    ('Luka Modrić', 'CRO', 'MF'),
    ('Ante Budimir', 'CRO', 'FW'),
    ('Ivor Pandur', 'CRO', 'GK'),
    ('Nikola Vlašić', 'CRO', 'MF'),
    ('Ivan Perišić', 'CRO', 'FW'),
    ('Mario Pašalić', 'CRO', 'MF'),
    ('Martin Baturina', 'CRO', 'MF'),
    ('Petar Sučić', 'CRO', 'MF'),
    ('Kristijan Jakić', 'CRO', 'DF'),
    ('Toni Fruk', 'CRO', 'MF'),
    ('Igor Matanović', 'CRO', 'FW'),
    ('Luka Sučić', 'CRO', 'MF'),
    ('Luka Vušković', 'CRO', 'DF'),
    ('Dominik Kotarski', 'CRO', 'GK'),
    ('Marco Pašalić', 'CRO', 'FW'),
    ('Martin Erlić', 'CRO', 'DF'),
    ('Petar Musa', 'CRO', 'FW'),
    ('Jordan Pickford', 'ENG', 'GK'),
    ('Ezri Konsa', 'ENG', 'DF'),
    ('Nico O''Reilly', 'ENG', 'DF'),
    ('Declan Rice', 'ENG', 'MF'),
    ('John Stones', 'ENG', 'DF'),
    ('Marc Guéhi', 'ENG', 'DF'),
    ('Bukayo Saka', 'ENG', 'FW'),
    ('Elliot Anderson', 'ENG', 'MF'),
    ('Harry Kane', 'ENG', 'FW'),
    ('Jude Bellingham', 'ENG', 'MF'),
    ('Marcus Rashford', 'ENG', 'FW'),
    ('Tino Livramento', 'ENG', 'DF'),
    ('Dean Henderson', 'ENG', 'GK'),
    ('Jordan Henderson', 'ENG', 'MF'),
    ('Dan Burn', 'ENG', 'DF'),
    ('Kobbie Mainoo', 'ENG', 'MF'),
    ('Morgan Rogers', 'ENG', 'MF'),
    ('Anthony Gordon', 'ENG', 'FW'),
    ('Ollie Watkins', 'ENG', 'FW'),
    ('Noni Madueke', 'ENG', 'FW'),
    ('Eberechi Eze', 'ENG', 'MF'),
    ('Ivan Toney', 'ENG', 'FW'),
    ('James Trafford', 'ENG', 'GK'),
    ('Reece James', 'ENG', 'DF'),
    ('Djed Spence', 'ENG', 'DF'),
    ('Jarell Quansah', 'ENG', 'DF'),
    ('Lawrence Ati-Zigi', 'GHA', 'GK'),
    ('Alidu Seidu', 'GHA', 'DF'),
    ('Caleb Yirenkyi', 'GHA', 'MF'),
    ('Jonas Adjetey', 'GHA', 'DF'),
    ('Thomas Partey', 'GHA', 'MF'),
    ('Abdul Mumin', 'GHA', 'DF'),
    ('Abdul Fatawu', 'GHA', 'FW'),
    ('Kwasi Sibo', 'GHA', 'MF'),
    ('Jordan Ayew', 'GHA', 'FW'),
    ('Brandon Thomas-Asante', 'GHA', 'FW'),
    ('Antoine Semenyo', 'GHA', 'MF'),
    ('Joseph Anang', 'GHA', 'GK'),
    ('Christopher Bonsu Baah', 'GHA', 'FW'),
    ('Gideon Mensah', 'GHA', 'DF'),
    ('Elisha Owusu', 'GHA', 'MF'),
    ('Benjamin Asare', 'GHA', 'GK'),
    ('Abdul Rahman Baba', 'GHA', 'DF'),
    ('Jerome Opoku', 'GHA', 'DF'),
    ('Iñaki Williams', 'GHA', 'FW'),
    ('Augustine Boakye', 'GHA', 'MF'),
    ('Kojo Peprah Oppong', 'GHA', 'DF'),
    ('Kamaldeen Sulemana', 'GHA', 'FW'),
    ('Derrick Luckassen', 'GHA', 'DF'),
    ('Ernest Nuamah', 'GHA', 'FW'),
    ('Prince Kwabena Adu', 'GHA', 'FW'),
    ('Marvin Senaya', 'GHA', 'DF'),
    ('Luis Mejía', 'PAN', 'GK'),
    ('César Blackman', 'PAN', 'DF'),
    ('José Córdoba', 'PAN', 'DF'),
    ('Fidel Escobar', 'PAN', 'DF'),
    ('Edgardo Fariña', 'PAN', 'DF'),
    ('Cristian Martínez', 'PAN', 'MF'),
    ('José Luis Rodríguez', 'PAN', 'MF'),
    ('Adalberto Carrasquilla', 'PAN', 'MF'),
    ('Tomás Rodríguez', 'PAN', 'FW'),
    ('Ismael Díaz', 'PAN', 'MF'),
    ('Yoel Bárcenas', 'PAN', 'MF'),
    ('César Samudio', 'PAN', 'GK'),
    ('Jiovany Ramos', 'PAN', 'DF'),
    ('Carlos Harvey', 'PAN', 'DF'),
    ('Eric Davis', 'PAN', 'DF'),
    ('Andrés Andrade', 'PAN', 'DF'),
    ('José Fajardo', 'PAN', 'FW'),
    ('Cecilio Waterman', 'PAN', 'FW'),
    ('Alberto Quintero', 'PAN', 'MF'),
    ('Aníbal Godoy', 'PAN', 'MF'),
    ('César Yanis', 'PAN', 'MF'),
    ('Orlando Mosquera', 'PAN', 'GK'),
    ('Michael Amir Murillo', 'PAN', 'DF'),
    ('Azarias Londoño', 'PAN', 'FW'),
    ('Roderick Miller', 'PAN', 'DF'),
    ('Jorge Gutiérrez', 'PAN', 'DF')
)
insert into public.players (name, team_id, position, is_active)
select player_rows.name, teams.id, player_rows.position, true
from player_rows
join public.teams on teams.short_name = player_rows.short_name
on conflict (team_id, name) do update set
  position = excluded.position,
  is_active = true;

with featured_player_rows(name, short_name, position, scorer_rank) as (
  values
    ('Kylian Mbappé', 'FRA', 'FW', 1),
    ('Harry Kane', 'ENG', 'FW', 2),
    ('Lionel Messi', 'ARG', 'FW', 3),
    ('Erling Haaland', 'NOR', 'FW', 4),
    ('Lamine Yamal', 'ESP', 'FW', 5),
    ('Mikel Oyarzabal', 'ESP', 'FW', 6),
    ('Vinícius Júnior', 'BRA', 'FW', 7),
    ('Ousmane Dembélé', 'FRA', 'FW', 8),
    ('Raphinha', 'BRA', 'FW', 9),
    ('Cristiano Ronaldo', 'POR', 'FW', 10),
    ('Lautaro Martínez', 'ARG', 'FW', 11),
    ('Luis Díaz', 'COL', 'FW', 12),
    ('Ferran Torres', 'ESP', 'FW', 13),
    ('Bruno Fernandes', 'POR', 'MF', 14),
    ('Viktor Gyökeres', 'SWE', 'FW', 15),
    ('Alexander Isak', 'SWE', 'FW', 16),
    ('Romelu Lukaku', 'BEL', 'FW', 17),
    ('Julián Alvarez', 'ARG', 'FW', 18),
    ('Bukayo Saka', 'ENG', 'FW', 19),
    ('Michael Olise', 'FRA', 'FW', 20),
    ('Neymar', 'BRA', 'FW', 21),
    ('Cody Gakpo', 'NED', 'FW', 22),
    ('Darwin Núñez', 'URU', 'FW', 23),
    ('Kai Havertz', 'GER', 'FW', 24),
    ('Jude Bellingham', 'ENG', 'MF', 25),
    ('Marcus Rashford', 'ENG', 'FW', 26),
    ('Jamal Musiala', 'GER', 'MF', 27),
    ('Florian Wirtz', 'GER', 'MF', 28),
    ('Memphis Depay', 'NED', 'FW', 29),
    ('Mohamed Salah', 'EGY', 'FW', 30),
    ('Sadio Mané', 'SEN', 'FW', 31),
    ('Christian Pulisic', 'USA', 'FW', 32),
    ('Son Heung-min', 'KOR', 'FW', 33),
    ('Takefusa Kubo', 'JPN', 'FW', 34),
    ('Salem Al-Dawsari', 'KSA', 'FW', 35),
    ('Enner Valencia', 'ECU', 'FW', 36),
    ('Mehdi Taremi', 'IRN', 'FW', 37),
    ('Rafael Leão', 'POR', 'FW', 38),
    ('Bernardo Silva', 'POR', 'MF', 39),
    ('Folarin Balogun', 'USA', 'FW', 40),
    ('Jonathan David', 'CAN', 'FW', 41),
    ('Santiago Giménez', 'MEX', 'FW', 42),
    ('Gonçalo Ramos', 'POR', 'FW', 43)
)
update public.players
set is_star = true,
    scorer_rank = featured_player_rows.scorer_rank,
    position = featured_player_rows.position,
    is_active = true
from featured_player_rows
join public.teams on teams.short_name = featured_player_rows.short_name
where public.players.team_id = teams.id
  and public.players.name = featured_player_rows.name;

insert into public.players (name, team_id, position, is_star, scorer_rank, is_active)
select
  'Jugador referencia ' || teams.short_name,
  teams.id,
  'FW',
  false,
  900 + row_number() over (order by teams.short_name),
  true
from public.teams teams
where not exists (
  select 1
  from public.players players
  where players.team_id = teams.id
)
on conflict (team_id, name) do update set
  position = excluded.position,
  is_star = excluded.is_star,
  scorer_rank = excluded.scorer_rank,
  is_active = true;

delete from public.matches
where match_number is null;

with match_rows(match_number, stage, group_letter, home_short, away_short, match_date, venue, home_placeholder, away_placeholder) as (
  values
    (1, 'group', 'A', 'MEX', 'RSA', '2026-06-11 15:00:00-04'::timestamptz, 'Mexico City Stadium', null, null),
    (2, 'group', 'A', 'KOR', 'CZE', '2026-06-11 22:00:00-04'::timestamptz, 'Estadio Guadalajara', null, null),
    (3, 'group', 'B', 'CAN', 'BIH', '2026-06-12 15:00:00-04'::timestamptz, 'Toronto Stadium', null, null),
    (4, 'group', 'D', 'USA', 'PAR', '2026-06-12 21:00:00-04'::timestamptz, 'Los Angeles Stadium', null, null),
    (5, 'group', 'C', 'HAI', 'SCO', '2026-06-13 21:00:00-04'::timestamptz, 'Boston Stadium', null, null),
    (6, 'group', 'D', 'AUS', 'TUR', '2026-06-14 00:00:00-04'::timestamptz, 'BC Place Vancouver', null, null),
    (7, 'group', 'C', 'BRA', 'MAR', '2026-06-13 18:00:00-04'::timestamptz, 'New York New Jersey Stadium', null, null),
    (8, 'group', 'B', 'QAT', 'SUI', '2026-06-13 15:00:00-04'::timestamptz, 'San Francisco Bay Area Stadium', null, null),
    (9, 'group', 'E', 'CIV', 'ECU', '2026-06-14 19:00:00-04'::timestamptz, 'Philadelphia Stadium', null, null),
    (10, 'group', 'E', 'GER', 'CUW', '2026-06-14 13:00:00-04'::timestamptz, 'Houston Stadium', null, null),
    (11, 'group', 'F', 'NED', 'JPN', '2026-06-14 16:00:00-04'::timestamptz, 'Dallas Stadium', null, null),
    (12, 'group', 'F', 'SWE', 'TUN', '2026-06-14 22:00:00-04'::timestamptz, 'Estadio Monterrey', null, null),
    (13, 'group', 'H', 'KSA', 'URU', '2026-06-15 18:00:00-04'::timestamptz, 'Miami Stadium', null, null),
    (14, 'group', 'H', 'ESP', 'CPV', '2026-06-15 12:00:00-04'::timestamptz, 'Atlanta Stadium', null, null),
    (15, 'group', 'G', 'IRN', 'NZL', '2026-06-15 21:00:00-04'::timestamptz, 'Los Angeles Stadium', null, null),
    (16, 'group', 'G', 'BEL', 'EGY', '2026-06-15 15:00:00-04'::timestamptz, 'Seattle Stadium', null, null),
    (17, 'group', 'I', 'FRA', 'SEN', '2026-06-16 15:00:00-04'::timestamptz, 'New York New Jersey Stadium', null, null),
    (18, 'group', 'I', 'NOR', 'IRQ', '2026-06-16 18:00:00-04'::timestamptz, 'Boston Stadium', null, null),
    (19, 'group', 'J', 'ARG', 'ALG', '2026-06-16 21:00:00-04'::timestamptz, 'Kansas City Stadium', null, null),
    (20, 'group', 'J', 'AUT', 'JOR', '2026-06-17 00:00:00-04'::timestamptz, 'San Francisco Bay Area Stadium', null, null),
    (21, 'group', 'L', 'GHA', 'PAN', '2026-06-17 19:00:00-04'::timestamptz, 'Toronto Stadium', null, null),
    (22, 'group', 'L', 'ENG', 'CRO', '2026-06-17 16:00:00-04'::timestamptz, 'Dallas Stadium', null, null),
    (23, 'group', 'K', 'POR', 'COD', '2026-06-17 13:00:00-04'::timestamptz, 'Houston Stadium', null, null),
    (24, 'group', 'K', 'UZB', 'COL', '2026-06-17 22:00:00-04'::timestamptz, 'Mexico City Stadium', null, null),
    (25, 'group', 'A', 'CZE', 'RSA', '2026-06-18 12:00:00-04'::timestamptz, 'Atlanta Stadium', null, null),
    (26, 'group', 'B', 'SUI', 'BIH', '2026-06-18 15:00:00-04'::timestamptz, 'Los Angeles Stadium', null, null),
    (27, 'group', 'B', 'CAN', 'QAT', '2026-06-18 18:00:00-04'::timestamptz, 'BC Place Vancouver', null, null),
    (28, 'group', 'A', 'MEX', 'KOR', '2026-06-18 21:00:00-04'::timestamptz, 'Estadio Guadalajara', null, null),
    (29, 'group', 'C', 'BRA', 'HAI', '2026-06-19 20:30:00-04'::timestamptz, 'Philadelphia Stadium', null, null),
    (30, 'group', 'C', 'SCO', 'MAR', '2026-06-19 18:00:00-04'::timestamptz, 'Boston Stadium', null, null),
    (31, 'group', 'D', 'TUR', 'PAR', '2026-06-19 23:00:00-04'::timestamptz, 'San Francisco Bay Area Stadium', null, null),
    (32, 'group', 'D', 'USA', 'AUS', '2026-06-19 15:00:00-04'::timestamptz, 'Seattle Stadium', null, null),
    (33, 'group', 'E', 'GER', 'CIV', '2026-06-20 16:00:00-04'::timestamptz, 'Toronto Stadium', null, null),
    (34, 'group', 'E', 'ECU', 'CUW', '2026-06-20 20:00:00-04'::timestamptz, 'Kansas City Stadium', null, null),
    (35, 'group', 'F', 'NED', 'SWE', '2026-06-20 13:00:00-04'::timestamptz, 'Houston Stadium', null, null),
    (36, 'group', 'F', 'TUN', 'JPN', '2026-06-21 00:00:00-04'::timestamptz, 'Estadio Monterrey', null, null),
    (37, 'group', 'H', 'URU', 'CPV', '2026-06-21 18:00:00-04'::timestamptz, 'Miami Stadium', null, null),
    (38, 'group', 'H', 'ESP', 'KSA', '2026-06-21 12:00:00-04'::timestamptz, 'Atlanta Stadium', null, null),
    (39, 'group', 'G', 'BEL', 'IRN', '2026-06-21 15:00:00-04'::timestamptz, 'Los Angeles Stadium', null, null),
    (40, 'group', 'G', 'NZL', 'EGY', '2026-06-21 21:00:00-04'::timestamptz, 'BC Place Vancouver', null, null),
    (41, 'group', 'I', 'NOR', 'SEN', '2026-06-22 20:00:00-04'::timestamptz, 'New York New Jersey Stadium', null, null),
    (42, 'group', 'I', 'FRA', 'IRQ', '2026-06-22 17:00:00-04'::timestamptz, 'Philadelphia Stadium', null, null),
    (43, 'group', 'J', 'ARG', 'AUT', '2026-06-22 13:00:00-04'::timestamptz, 'Dallas Stadium', null, null),
    (44, 'group', 'J', 'JOR', 'ALG', '2026-06-22 23:00:00-04'::timestamptz, 'San Francisco Bay Area Stadium', null, null),
    (45, 'group', 'L', 'ENG', 'GHA', '2026-06-23 16:00:00-04'::timestamptz, 'Boston Stadium', null, null),
    (46, 'group', 'L', 'PAN', 'CRO', '2026-06-23 19:00:00-04'::timestamptz, 'Toronto Stadium', null, null),
    (47, 'group', 'K', 'POR', 'UZB', '2026-06-23 13:00:00-04'::timestamptz, 'Houston Stadium', null, null),
    (48, 'group', 'K', 'COL', 'COD', '2026-06-23 22:00:00-04'::timestamptz, 'Estadio Guadalajara', null, null),
    (49, 'group', 'C', 'SCO', 'BRA', '2026-06-24 18:00:00-04'::timestamptz, 'Miami Stadium', null, null),
    (50, 'group', 'C', 'MAR', 'HAI', '2026-06-24 18:00:00-04'::timestamptz, 'Atlanta Stadium', null, null),
    (51, 'group', 'B', 'SUI', 'CAN', '2026-06-24 15:00:00-04'::timestamptz, 'BC Place Vancouver', null, null),
    (52, 'group', 'B', 'BIH', 'QAT', '2026-06-24 15:00:00-04'::timestamptz, 'Seattle Stadium', null, null),
    (53, 'group', 'A', 'CZE', 'MEX', '2026-06-24 21:00:00-04'::timestamptz, 'Mexico City Stadium', null, null),
    (54, 'group', 'A', 'RSA', 'KOR', '2026-06-24 21:00:00-04'::timestamptz, 'Estadio Monterrey', null, null),
    (55, 'group', 'E', 'CUW', 'CIV', '2026-06-25 16:00:00-04'::timestamptz, 'Philadelphia Stadium', null, null),
    (56, 'group', 'E', 'ECU', 'GER', '2026-06-25 16:00:00-04'::timestamptz, 'New York New Jersey Stadium', null, null),
    (57, 'group', 'F', 'JPN', 'SWE', '2026-06-25 19:00:00-04'::timestamptz, 'Dallas Stadium', null, null),
    (58, 'group', 'F', 'TUN', 'NED', '2026-06-25 19:00:00-04'::timestamptz, 'Kansas City Stadium', null, null),
    (59, 'group', 'D', 'TUR', 'USA', '2026-06-25 22:00:00-04'::timestamptz, 'Los Angeles Stadium', null, null),
    (60, 'group', 'D', 'PAR', 'AUS', '2026-06-25 22:00:00-04'::timestamptz, 'San Francisco Bay Area Stadium', null, null),
    (61, 'group', 'I', 'NOR', 'FRA', '2026-06-26 15:00:00-04'::timestamptz, 'Boston Stadium', null, null),
    (62, 'group', 'I', 'SEN', 'IRQ', '2026-06-26 15:00:00-04'::timestamptz, 'Toronto Stadium', null, null),
    (63, 'group', 'G', 'EGY', 'IRN', '2026-06-26 23:00:00-04'::timestamptz, 'Seattle Stadium', null, null),
    (64, 'group', 'G', 'NZL', 'BEL', '2026-06-26 23:00:00-04'::timestamptz, 'BC Place Vancouver', null, null),
    (65, 'group', 'H', 'CPV', 'KSA', '2026-06-26 20:00:00-04'::timestamptz, 'Houston Stadium', null, null),
    (66, 'group', 'H', 'URU', 'ESP', '2026-06-26 20:00:00-04'::timestamptz, 'Estadio Guadalajara', null, null),
    (67, 'group', 'L', 'PAN', 'ENG', '2026-06-27 17:00:00-04'::timestamptz, 'New York New Jersey Stadium', null, null),
    (68, 'group', 'L', 'CRO', 'GHA', '2026-06-27 17:00:00-04'::timestamptz, 'Philadelphia Stadium', null, null),
    (69, 'group', 'J', 'ALG', 'AUT', '2026-06-27 22:00:00-04'::timestamptz, 'Kansas City Stadium', null, null),
    (70, 'group', 'J', 'JOR', 'ARG', '2026-06-27 22:00:00-04'::timestamptz, 'Dallas Stadium', null, null),
    (71, 'group', 'K', 'COL', 'POR', '2026-06-27 19:30:00-04'::timestamptz, 'Miami Stadium', null, null),
    (72, 'group', 'K', 'UZB', 'COD', '2026-06-27 19:30:00-04'::timestamptz, 'Atlanta Stadium', null, null),
    (73, 'round_32', null, null, null, '2026-06-28 15:00:00-04'::timestamptz, 'Los Angeles Stadium', '2º Grupo A', '2º Grupo B'),
    (74, 'round_32', null, null, null, '2026-06-29 16:30:00-04'::timestamptz, 'Boston Stadium', '1º Grupo E', '3º Grupo A/B/C/D/F'),
    (75, 'round_32', null, null, null, '2026-06-29 21:00:00-04'::timestamptz, 'Estadio Monterrey', '1º Grupo F', '2º Grupo C'),
    (76, 'round_32', null, null, null, '2026-06-29 13:00:00-04'::timestamptz, 'Houston Stadium', '1º Grupo C', '2º Grupo F'),
    (77, 'round_32', null, null, null, '2026-06-30 17:00:00-04'::timestamptz, 'New York New Jersey Stadium', '1º Grupo I', '3º Grupo C/D/F/G/H'),
    (78, 'round_32', null, null, null, '2026-06-30 13:00:00-04'::timestamptz, 'Dallas Stadium', '2º Grupo E', '2º Grupo I'),
    (79, 'round_32', null, null, null, '2026-06-30 21:00:00-04'::timestamptz, 'Mexico City Stadium', '1º Grupo A', '3º Grupo C/E/F/H/I'),
    (80, 'round_32', null, null, null, '2026-07-01 12:00:00-04'::timestamptz, 'Atlanta Stadium', '1º Grupo L', '3º Grupo E/H/I/J/K'),
    (81, 'round_32', null, null, null, '2026-07-01 20:00:00-04'::timestamptz, 'San Francisco Bay Area Stadium', '1º Grupo D', '3º Grupo B/E/F/I/J'),
    (82, 'round_32', null, null, null, '2026-07-01 16:00:00-04'::timestamptz, 'Seattle Stadium', '1º Grupo G', '3º Grupo A/E/H/I/J'),
    (83, 'round_32', null, null, null, '2026-07-02 19:00:00-04'::timestamptz, 'Toronto Stadium', '2º Grupo K', '2º Grupo L'),
    (84, 'round_32', null, null, null, '2026-07-02 15:00:00-04'::timestamptz, 'Los Angeles Stadium', '1º Grupo H', '2º Grupo J'),
    (85, 'round_32', null, null, null, '2026-07-02 23:00:00-04'::timestamptz, 'BC Place Vancouver', '1º Grupo B', '3º Grupo E/F/G/I/J'),
    (86, 'round_32', null, null, null, '2026-07-03 18:00:00-04'::timestamptz, 'Miami Stadium', '1º Grupo J', '2º Grupo H'),
    (87, 'round_32', null, null, null, '2026-07-03 21:30:00-04'::timestamptz, 'Kansas City Stadium', '1º Grupo K', '3º Grupo D/E/I/J/L'),
    (88, 'round_32', null, null, null, '2026-07-03 14:00:00-04'::timestamptz, 'Dallas Stadium', '2º Grupo D', '2º Grupo G'),
    (89, 'round_16', null, null, null, '2026-07-04 17:00:00-04'::timestamptz, 'Philadelphia Stadium', 'Ganador partido 74', 'Ganador partido 77'),
    (90, 'round_16', null, null, null, '2026-07-04 13:00:00-04'::timestamptz, 'Houston Stadium', 'Ganador partido 73', 'Ganador partido 75'),
    (91, 'round_16', null, null, null, '2026-07-05 16:00:00-04'::timestamptz, 'New York New Jersey Stadium', 'Ganador partido 76', 'Ganador partido 78'),
    (92, 'round_16', null, null, null, '2026-07-05 20:00:00-04'::timestamptz, 'Mexico City Stadium', 'Ganador partido 79', 'Ganador partido 80'),
    (93, 'round_16', null, null, null, '2026-07-06 15:00:00-04'::timestamptz, 'Dallas Stadium', 'Ganador partido 83', 'Ganador partido 84'),
    (94, 'round_16', null, null, null, '2026-07-06 20:00:00-04'::timestamptz, 'Seattle Stadium', 'Ganador partido 81', 'Ganador partido 82'),
    (95, 'round_16', null, null, null, '2026-07-07 12:00:00-04'::timestamptz, 'Atlanta Stadium', 'Ganador partido 86', 'Ganador partido 88'),
    (96, 'round_16', null, null, null, '2026-07-07 16:00:00-04'::timestamptz, 'BC Place Vancouver', 'Ganador partido 85', 'Ganador partido 87'),
    (97, 'quarter_final', null, null, null, '2026-07-09 16:00:00-04'::timestamptz, 'Boston Stadium', 'Ganador partido 89', 'Ganador partido 90'),
    (98, 'quarter_final', null, null, null, '2026-07-10 15:00:00-04'::timestamptz, 'Los Angeles Stadium', 'Ganador partido 93', 'Ganador partido 94'),
    (99, 'quarter_final', null, null, null, '2026-07-11 17:00:00-04'::timestamptz, 'Miami Stadium', 'Ganador partido 91', 'Ganador partido 92'),
    (100, 'quarter_final', null, null, null, '2026-07-11 21:00:00-04'::timestamptz, 'Kansas City Stadium', 'Ganador partido 95', 'Ganador partido 96'),
    (101, 'semi_final', null, null, null, '2026-07-14 15:00:00-04'::timestamptz, 'Dallas Stadium', 'Ganador partido 97', 'Ganador partido 98'),
    (102, 'semi_final', null, null, null, '2026-07-15 15:00:00-04'::timestamptz, 'Atlanta Stadium', 'Ganador partido 99', 'Ganador partido 100'),
    (103, 'third_place', null, null, null, '2026-07-18 17:00:00-04'::timestamptz, 'Miami Stadium', 'Perdedor partido 101', 'Perdedor partido 102'),
    (104, 'final', null, null, null, '2026-07-19 15:00:00-04'::timestamptz, 'New York New Jersey Stadium', 'Ganador partido 101', 'Ganador partido 102')
)
insert into public.matches
  (match_number, stage, group_letter, home_team_id, away_team_id, match_date, venue, home_placeholder, away_placeholder)
select
  match_rows.match_number,
  match_rows.stage::public.match_stage,
  match_rows.group_letter,
  home_team.id,
  away_team.id,
  match_rows.match_date,
  match_rows.venue,
  match_rows.home_placeholder,
  match_rows.away_placeholder
from match_rows
left join public.teams home_team on home_team.short_name = match_rows.home_short
left join public.teams away_team on away_team.short_name = match_rows.away_short
on conflict (match_number) do update set
  stage = excluded.stage,
  group_letter = excluded.group_letter,
  home_team_id = coalesce(excluded.home_team_id, public.matches.home_team_id),
  away_team_id = coalesce(excluded.away_team_id, public.matches.away_team_id),
  match_date = excluded.match_date,
  venue = excluded.venue,
  home_placeholder = excluded.home_placeholder,
  away_placeholder = excluded.away_placeholder;

-- El usuario admin inicial debe crearse en Supabase Auth.
-- Opción recomendada: usa el script del README con ADMIN_EMAIL y ADMIN_PASSWORD.
-- Después ejecuta:
-- update public.profiles set role = 'admin' where email = 'admin@porra.local';

